/** Legacy POS labels merged from create-vocab-games.js and update-all-vocab.js */
module.exports = {
  "addiction": "noun",
  "affordable": "adjective",
  "ambitious": "adjective",
  "background": "noun",
  "barrier": "noun",
  "behavior": "noun",
  "beneficial": "adjective",
  "bladder": "noun",
  "burnout": "noun",
  "cardiologist": "noun",
  "commission": "noun",
  "commitment": "noun",
  "concentrate": "verb",
  "coordinate": "verb",
  "coping skills": "noun",
  "courtesy": "noun",
  "courthouse": "noun",
  "criticize": "verb",
  "decision-making": "noun",
  "deductions": "noun",
  "deposit": "noun",
  "depressed": "adjective",
  "detail-oriented": "adjective",
  "disadvantages": "noun",
  "distraction": "noun",
  "enthusiasm": "noun",
  "entry-level": "adjective",
  "environment": "noun",
  "equivalent": "adjective",
  "errands": "noun",
  "expire": "verb",
  "fast-paced": "adjective",
  "fluent": "adjective",
  "fundraiser": "noun",
  "go over": "phrasal verb",
  "gross pay": "noun",
  "harmful": "adjective",
  "hydration": "noun",
  "immigration": "noun",
  "improve": "verb",
  "included": "adjective",
  "infected": "adjective",
  "inflamed": "adjective",
  "installation": "noun",
  "installments": "noun",
  "kidneys": "noun",
  "landlord": "noun",
  "lease": "noun",
  "liver": "noun",
  "maintenance": "noun",
  "moderation": "noun",
  "motivation": "noun",
  "navigate": "verb",
  "networking": "noun",
  "obstacle": "noun",
  "opportunity": "noun",
  "outgoing": "adjective",
  "outlet": "noun",
  "pancreas": "noun",
  "pediatrician": "noun",
  "personal growth": "noun",
  "preferences": "noun",
  "prior": "adjective",
  "professional development": "noun",
  "property": "noun",
  "qualification": "noun",
  "recreational": "adjective",
  "recruit": "verb",
  "refund": "noun",
  "regimen": "noun",
  "registration": "noun",
  "reliable": "adjective",
  "relocate": "verb",
  "reserved": "adjective",
  "role": "noun",
  "scam": "noun",
  "self-confidence": "noun",
  "self-esteem": "noun",
  "spacious": "adjective",
  "stable": "adjective",
  "strict": "adjective",
  "stroke": "noun",
  "sustain": "verb",
  "tab": "noun",
  "take on": "phrasal verb",
  "tenant": "noun",
  "transition": "noun",
  "under pressure": "phrase",
  "urgently": "adverb",
  "utilities": "noun",
  "vocational": "adjective",
  "waived": "verb",
  "warranty": "noun",
  "well-being": "noun",
};
