// Re-export from new location for backward compatibility
export {
  parseApiBody,
  ActivitySubmitBodySchema,
  SubmissionsPostBodySchema,
  ClassesPostBodySchema,
  JoinClassBodySchema,
  AssignmentPatchBodySchema,
  FeedbackPostBodySchema,
  CalendarEventPostBodySchema,
  CalendarEventPatchBodySchema,
  AssignmentPostBodySchema,
  type ActivitySubmitBody,
  type SubmissionsPostBody,
  type ClassesPostBody,
  type JoinClassBody,
  type AssignmentPatchBody,
  type FeedbackPostBody,
  type CalendarEventPostBody,
  type CalendarEventPatchBody,
  type AssignmentPostBody,
} from "./api/schemas";
