// Re-export from new location for backward compatibility
export {
  ValidationError,
  validateUserId,
  validateClassCode,
  validateProgress,
  validateOptionalProgress,
  validatePassword,
  validateString,
  validateInteger,
  validateEmail,
  validateEnum,
  validateArray,
  validateBoolean,
  validateActivityType,
  validateUserRole,
  parseRequestBody,
  ACTIVITY_TYPES,
  USER_ROLES,
  type ActivityType,
  type UserRole,
} from "./shared/validators";
