export const POINTS = {
  QUIZ_PERFECT_SCORE: 15,
  QUIZ_HIGH_SCORE: 10,
  QUIZ_GOOD_SCORE: 5,
  QUIZ_PASSING_SCORE: 2,

  FLASHCARDS: 4,
  MATCHING_GAME: 5,
  FILL_IN_BLANK: 7,

  NUMBERS_GAME_EASY: 3,
  NUMBERS_GAME_MEDIUM: 5,
  NUMBERS_GAME_MEDIUM_HARD: 7,
  NUMBERS_GAME_HARD: 10,
  VERB_FORMS_EASY: 1,
  VERB_FORMS_MEDIUM: 2,
  VERB_FORMS_HARD: 3,
  VERB_FORMS_BONUS: 5,

  NUMBERS_GAME_PERFECT_EASY: 2,
  NUMBERS_GAME_HIGH_EASY: 1,

  NUMBERS_GAME_PERFECT_MEDIUM: 3,
  NUMBERS_GAME_HIGH_MEDIUM: 2,

  NUMBERS_GAME_PERFECT_MEDIUM_HARD: 5,
  NUMBERS_GAME_HIGH_MEDIUM_HARD: 3,

  NUMBERS_GAME_PERFECT_HARD: 7,
  NUMBERS_GAME_HIGH_HARD: 4,

  GRAMMAR_GUIDE: 10,
  GRAMMAR_EXERCISE: 2,
  GRAMMAR_GUIDE_BASE: 5,
  GRAMMAR_GUIDE_PERFECT_BONUS: 5,
  SPEAKING_ACTIVITY: 6,
  ED_PRONUNCIATION: 6,
  ED_PRONUNCIATION_PERFECT: 10,
  MINIMAL_PAIRS: 6,
  ACTIVITY_COMPLETION: 3,

  DAILY_STREAK: 3,
  WEEKLY_STREAK: 25,

  ACHIEVEMENT_BONUS: 50,
} as const;

export type PointsKey = keyof typeof POINTS;
