import type { VerbData } from "@/types/verb-quiz";

const VERB_DEFINITIONS: Record<string, string> = {
  achieve: "to succeed in doing something after effort",
  address: "to deal with a problem or speak to someone",
  apply: "to ask for something officially or put something on",
  ask: "to say something to get information or help",
  avoid: "to stay away from something or prevent it",
  be: "to exist or have a certain state",
  become: "to start to be or develop into something different",
  book: "to reserve something in advance",
  break: "to separate into pieces or stop working",
  breathe: "to take air into and out of your body",
  build: "to make something by putting parts together",
  bite: "to cut into food with your teeth",
  burst: "to break open suddenly",
  burn: "to use energy from food or to cook something too long",
  buy: "to get something by paying money",
  call: "to phone someone or shout a name",
  cancel: "to decide that something will not happen",
  chat: "to talk in a friendly informal way",
  choose: "to decide which thing or person you want",
  come: "to move toward a place or person",
  confirm: "to say that something is true or definite",
  comply: "to follow a rule or do what is required",
  consume: "to eat, drink, or use something",
  contact: "to communicate with someone",
  cook: "to prepare food with heat",
  cost: "to have a price",
  deal: "to handle a situation, often as in deal with",
  discuss: "to talk about something together",
  do: "to perform an action or task",
  document: "to record information in writing",
  drink: "to take liquid into your mouth and swallow it",
  drive: "to control a car or other vehicle",
  eat: "to put food in your mouth and swallow it",
  examine: "to look at something carefully or check it",
  exercise: "to do physical activity to stay healthy",
  feed: "to give food to yourself, a child, or an animal",
  feel: "to experience an emotion or physical sensation",
  find: "to discover something or someone",
  forget: "to not remember something or fail to do something you planned",
  fix: "to repair something",
  fly: "to move through the air",
  forward: "to send a message to another person",
  freeze: "to become very cold and turn to ice",
  get: "to receive, obtain, or become",
  give: "to hand something to someone",
  go: "to move from one place to another",
  grow: "to become larger or develop",
  handle: "to manage or deal with something",
  have: "to own, hold, or experience something",
  hear: "to notice sound with your ears",
  heat: "to make something warm or hot",
  hold: "to keep something in your hands or arms",
  hurt: "to cause pain or feel pain",
  improve: "to make something better",
  keep: "to continue to have or hold something",
  know: "to have information or understanding in your mind",
  leak: "to let liquid or gas escape by accident",
  lead: "to guide or be in charge of a group",
  learn: "to get knowledge or a skill",
  leave: "to go away from a place",
  lend: "to give something temporarily and expect it back",
  make: "to create or produce something",
  mean: "to have a particular meaning or intention",
  meet: "to come together with someone",
  mention: "to speak briefly about something",
  mix: "to combine things together",
  need: "to require something because it is necessary",
  pay: "to give money for something",
  plan: "to decide in detail what you will do",
  practice: "to do something again and again to improve",
  prepare: "to get something ready",
  prescribe: "to officially say what medicine someone should take",
  read: "to look at written words and understand them",
  refill: "to fill something again",
  register: "to sign up or record information officially",
  reply: "to answer someone",
  report: "to give information about something",
  reschedule: "to arrange something for a different time",
  resolve: "to solve a problem",
  respond: "to answer or react",
  rest: "to relax or stop working",
  ride: "to travel on a bike, horse, or vehicle",
  run: "to move quickly on your feet",
  say: "to speak words",
  schedule: "to arrange a time for something",
  see: "to notice with your eyes",
  show: "to let someone see something or explain how to do it",
  sell: "to give something to someone for money",
  send: "to cause something to go to another place or person",
  sit: "to rest on a chair or other seat",
  sleep: "to rest with your eyes closed",
  solve: "to find the answer to a problem",
  speak: "to talk or use your voice",
  spoil: "when food goes bad and is no longer safe to eat",
  spread: "to cover bread or crackers with butter, jam, or another soft food",
  spend: "to use time or money",
  stand: "to be on your feet",
  store: "to keep something for future use",
  stretch: "to make something longer or extend your body",
  submit: "to give something officially for review",
  succeed: "to achieve the result you wanted",
  suggest: "to give an idea or recommendation",
  take: "to move something from one place to another or receive it",
  talk: "to speak with someone",
  teach: "to help someone learn",
  tell: "to give information or instructions",
  think: "to use your mind to form ideas or opinions",
  throw: "to send something through the air with your hand or arm",
  try: "to make an effort to do something",
  understand: "to know what something means",
  update: "to make something more current",
  use: "to do something with a tool or object",
  wake: "to stop sleeping or make someone stop sleeping",
  win: "to get first place or succeed in a competition",
  wear: "to have clothes or accessories on your body",
  work: "to do a job or function properly",
  write: "to form words on paper or a screen",
};

export function getVerbDefinition(verb: string, verbData?: VerbData): string | null {
  const explicitDefinition = verbData?.definition?.trim();
  if (explicitDefinition) {
    return explicitDefinition;
  }

  return VERB_DEFINITIONS[verb.trim().toLowerCase()] ?? null;
}
