import { PrismaClient } from '@prisma/client';
import type { GrammarHospitalCase, GrammarHospitalContent } from '../src/types/activity';

const prisma = new PrismaClient();

const ACTIVITY_TITLE = 'Grammar Hospital — Helper Verb Repair';

// Locate a substring inside `unhealthy` for the terracotta highlight.
// Throws at seed time if missing so a broken highlight never ships silently.
function span(unhealthy: string, target: string): [number, number] {
  const i = unhealthy.indexOf(target);
  if (i === -1) {
    throw new Error(`Highlight target "${target}" not found in: ${unhealthy}`);
  }
  return [i, i + target.length];
}

// ============================================================================
// BEGINNER (25)
// Focus: do-does, be-vs-do — simple present helpers
// ============================================================================
const beginnerCases: GrammarHospitalCase[] = [
  // ─── Wrong-helper QUESTIONS (8) ────────────────────────────────────────
  {
    id: 'b-q1',
    sentenceType: 'question',
    pattern: 'action',
    unhealthy: 'Are they work in the hospital?',
    highlightSpan: span('Are they work in the hospital?', 'Are'),
    errorTags: ['wrong-helper'],
    correctHelper: 'do',
    healthy: 'Do they work in the hospital?',
    wordBank: ['Do', 'they', 'work', 'in', 'the', 'hospital', '?'],
    subject: 'they',
    baseVerb: 'work',
    explanation: 'Use DO because "they" + an action verb (work). Save BE for states like tired, happy, a nurse.',
    hint: '"They" is plural and "work" is an action. Action verbs in simple present use do / does — not be.',
    tier: 'beginner', complexity: 1, grammarFocus: 'do-does',
  },
  {
    id: 'b-q2',
    sentenceType: 'question',
    pattern: 'action',
    unhealthy: 'Is she drive Uber?',
    highlightSpan: span('Is she drive Uber?', 'Is'),
    errorTags: ['wrong-helper'],
    correctHelper: 'does',
    healthy: 'Does she drive Uber?',
    wordBank: ['Does', 'she', 'drive', 'Uber', '?'],
    subject: 'she',
    baseVerb: 'drive',
    explanation: 'For "she / he / it" + an action verb, use DOES. The main verb stays in the base form: "drive", not "drives".',
    hint: '"She" needs DOES (third person). The verb after DOES stays in its base form.',
    tier: 'beginner', complexity: 2, grammarFocus: 'do-does',
  },
  {
    id: 'b-q3',
    sentenceType: 'question',
    pattern: 'action',
    unhealthy: 'Are you like coffee?',
    highlightSpan: span('Are you like coffee?', 'Are'),
    errorTags: ['wrong-helper'],
    correctHelper: 'do',
    healthy: 'Do you like coffee?',
    wordBank: ['Do', 'you', 'like', 'coffee', '?'],
    subject: 'you',
    baseVerb: 'like',
    explanation: '"Like" is an action / preference verb — use DO with "you". BE would only fit if the verb were a state word like "tired".',
    hint: '"You" + an action verb → DO.',
    tier: 'beginner', complexity: 1, grammarFocus: 'do-does',
  },
  {
    id: 'b-q4',
    sentenceType: 'question',
    pattern: 'action',
    unhealthy: 'Is he speak Spanish?',
    highlightSpan: span('Is he speak Spanish?', 'Is'),
    errorTags: ['wrong-helper'],
    correctHelper: 'does',
    healthy: 'Does he speak Spanish?',
    wordBank: ['Does', 'he', 'speak', 'Spanish', '?'],
    subject: 'he',
    baseVerb: 'speak',
    explanation: '"He" + an action verb (speak) needs DOES. Keep the main verb in base form.',
    hint: 'Third person ("he / she / it") with an action verb → DOES + base verb.',
    tier: 'beginner', complexity: 2, grammarFocus: 'do-does',
  },
  {
    id: 'b-q5',
    sentenceType: 'question',
    pattern: 'action',
    unhealthy: 'Are they study English every day?',
    highlightSpan: span('Are they study English every day?', 'Are'),
    errorTags: ['wrong-helper'],
    correctHelper: 'do',
    healthy: 'Do they study English every day?',
    wordBank: ['Do', 'they', 'study', 'English', 'every', 'day', '?'],
    subject: 'they',
    baseVerb: 'study',
    explanation: '"Study" is an action. "They" + action verb → DO. (BE would only work if you said "Are they studying…" with -ing.)',
    hint: 'Plural subject + action verb in simple present → DO.',
    tier: 'beginner', complexity: 2, grammarFocus: 'do-does',
  },
  {
    id: 'b-q6',
    sentenceType: 'question',
    pattern: 'action',
    unhealthy: 'Is the bus come at 8?',
    highlightSpan: span('Is the bus come at 8?', 'Is'),
    errorTags: ['wrong-helper'],
    correctHelper: 'does',
    healthy: 'Does the bus come at 8?',
    wordBank: ['Does', 'the', 'bus', 'come', 'at', '8', '?'],
    subject: 'the bus',
    baseVerb: 'come',
    explanation: '"The bus" is third person singular (like "it") and "come" is an action — use DOES.',
    hint: '"The bus" = "it" → DOES.',
    tier: 'beginner', complexity: 3, grammarFocus: 'do-does',
  },
  {
    id: 'b-q7',
    sentenceType: 'question',
    pattern: 'action',
    unhealthy: 'Are your kids go to school?',
    highlightSpan: span('Are your kids go to school?', 'Are'),
    errorTags: ['wrong-helper'],
    correctHelper: 'do',
    healthy: 'Do your kids go to school?',
    wordBank: ['Do', 'your', 'kids', 'go', 'to', 'school', '?'],
    subject: 'your kids',
    baseVerb: 'go',
    explanation: '"Your kids" = "they" → DO + base verb "go".',
    hint: 'Plural subject ("your kids") + action verb → DO.',
    tier: 'beginner', complexity: 2, grammarFocus: 'do-does',
  },
  {
    id: 'b-q8',
    sentenceType: 'question',
    pattern: 'action',
    unhealthy: 'Is your wife work nights?',
    highlightSpan: span('Is your wife work nights?', 'Is'),
    errorTags: ['wrong-helper'],
    correctHelper: 'does',
    healthy: 'Does your wife work nights?',
    wordBank: ['Does', 'your', 'wife', 'work', 'nights', '?'],
    subject: 'your wife',
    baseVerb: 'work',
    explanation: '"Your wife" = "she" → DOES. The main verb "work" stays in base form (not "works") after DOES.',
    hint: '"She" + action verb → DOES + base verb.',
    tier: 'beginner', complexity: 3, grammarFocus: 'do-does',
  },

  // ─── Wrong-helper NEGATIVES (5) ────────────────────────────────────────
  {
    id: 'b-n1',
    sentenceType: 'negative',
    pattern: 'action',
    unhealthy: 'They are not drive to work.',
    highlightSpan: span('They are not drive to work.', 'are not'),
    errorTags: ['wrong-helper'],
    correctHelper: 'do',
    healthy: "They don't drive to work.",
    acceptable: ['They do not drive to work.'],
    wordBank: ["don't", 'They', 'drive', 'to', 'work', '.'],
    subject: 'they',
    baseVerb: 'drive',
    explanation: 'Negate action verbs in simple present with DON\'T / DOESN\'T. "Are not" is for states (e.g. "They are not tired").',
    hint: 'Action verb negative → don\'t (plural) / doesn\'t (he/she/it).',
    tier: 'beginner', complexity: 2, grammarFocus: 'do-does',
  },
  {
    id: 'b-n2',
    sentenceType: 'negative',
    pattern: 'action',
    unhealthy: 'She is not like pizza.',
    highlightSpan: span('She is not like pizza.', 'is not'),
    errorTags: ['wrong-helper'],
    correctHelper: 'does',
    healthy: "She doesn't like pizza.",
    acceptable: ['She does not like pizza.'],
    wordBank: ["doesn't", 'She', 'like', 'pizza', '.'],
    subject: 'she',
    baseVerb: 'like',
    explanation: '"Like" is an action / preference verb — negate with DOESN\'T (third person). Main verb stays "like", not "likes".',
    hint: '"She" + negative action verb → doesn\'t + base verb.',
    tier: 'beginner', complexity: 2, grammarFocus: 'do-does',
  },
  {
    id: 'b-n3',
    sentenceType: 'negative',
    pattern: 'action',
    unhealthy: "He don't likes pizza.",
    highlightSpan: span("He don't likes pizza.", "don't likes"),
    errorTags: ['wrong-helper', 'verb-form'],
    correctHelper: 'does',
    healthy: "He doesn't like pizza.",
    acceptable: ['He does not like pizza.'],
    subject: 'he',
    baseVerb: 'like',
    explanation: 'Two problems: "He" needs DOESN\'T (not don\'t), and after doesn\'t the verb stays base form: "like", not "likes".',
    hint: 'Third person: doesn\'t + base verb. Only one of them gets the -s, never both.',
    tier: 'beginner', complexity: 4, grammarFocus: 'do-does',
  },
  {
    id: 'b-n4',
    sentenceType: 'negative',
    pattern: 'action',
    unhealthy: "We aren't work on Sundays.",
    highlightSpan: span("We aren't work on Sundays.", "aren't"),
    errorTags: ['wrong-helper'],
    correctHelper: 'do',
    healthy: "We don't work on Sundays.",
    acceptable: ['We do not work on Sundays.'],
    subject: 'we',
    baseVerb: 'work',
    explanation: '"Work" is an action verb. "We" + negative action → DON\'T. "Aren\'t" only works with states: "We aren\'t tired."',
    hint: 'Action verb negative → don\'t / doesn\'t, not aren\'t / isn\'t.',
    tier: 'beginner', complexity: 3, grammarFocus: 'do-does',
  },
  {
    id: 'b-n5',
    sentenceType: 'negative',
    pattern: 'action',
    unhealthy: 'I am not understand.',
    highlightSpan: span('I am not understand.', 'am not'),
    errorTags: ['wrong-helper'],
    correctHelper: 'do',
    healthy: "I don't understand.",
    acceptable: ['I do not understand.'],
    subject: 'I',
    baseVerb: 'understand',
    explanation: '"Understand" is an action / mental verb — use DON\'T with "I". "Am not" would be for a state: "I am not ready."',
    hint: '"I" + negative action verb → don\'t.',
    tier: 'beginner', complexity: 3, grammarFocus: 'do-does',
  },

  // ─── BE-overuse STATEMENTS / contrast (4) ──────────────────────────────
  {
    id: 'b-s1',
    sentenceType: 'statement',
    pattern: 'action',
    unhealthy: 'He is cook every day.',
    highlightSpan: span('He is cook every day.', 'is cook'),
    errorTags: ['wrong-helper', 'extra-word'],
    correctHelper: 'does',
    healthy: 'He cooks every day.',
    subject: 'he',
    baseVerb: 'cook',
    explanation: 'Simple present statements with an action verb need no helper at all — just add -s for he / she / it: "He cooks." BE doesn\'t belong here.',
    hint: 'Simple present action statements: subject + verb (+ -s for he/she/it). No "is".',
    tier: 'beginner', complexity: 3, grammarFocus: 'be-vs-do',
  },
  {
    id: 'b-s2',
    sentenceType: 'statement',
    pattern: 'state',
    unhealthy: 'She are a nurse.',
    highlightSpan: span('She are a nurse.', 'are'),
    errorTags: ['verb-form'],
    correctHelper: 'is',
    healthy: 'She is a nurse.',
    subject: 'she',
    baseVerb: 'be',
    explanation: 'BE is correct here because "a nurse" describes WHO she is — that\'s a state. But "she" takes IS, not ARE.',
    hint: 'BE for states is right, but match the form: I am · he/she/it is · we/you/they are.',
    tier: 'beginner', complexity: 2, grammarFocus: 'be-vs-do',
  },
  {
    id: 'b-s3',
    sentenceType: 'statement',
    pattern: 'action',
    unhealthy: 'They is working hard.',
    highlightSpan: span('They is working hard.', 'is'),
    errorTags: ['verb-form'],
    correctHelper: 'are',
    healthy: 'They are working hard.',
    subject: 'they',
    baseVerb: 'work',
    explanation: 'BE is correct here (present continuous: BE + -ing), but "they" needs ARE — not IS. I am · he/she/it is · we/you/they are.',
    hint: 'Present continuous = BE + verb-ing. Match BE to the subject.',
    tier: 'beginner', complexity: 3, grammarFocus: 'be-vs-do',
  },
  {
    id: 'b-s4',
    sentenceType: 'statement',
    pattern: 'action',
    unhealthy: 'My brother is drive a taxi.',
    highlightSpan: span('My brother is drive a taxi.', 'is drive'),
    errorTags: ['wrong-helper', 'extra-word'],
    correctHelper: 'does',
    healthy: 'My brother drives a taxi.',
    subject: 'my brother',
    baseVerb: 'drive',
    explanation: 'For simple present action statements, drop the helper completely and add -s for he/she/it: "My brother drives a taxi."',
    hint: 'No "is" needed. Subject + verb + -s (for he/she/it).',
    tier: 'beginner', complexity: 4, grammarFocus: 'be-vs-do',
  },

  // ─── Missing word (3) ──────────────────────────────────────────────────
  {
    id: 'b-m1',
    sentenceType: 'question',
    pattern: 'action',
    unhealthy: 'They work here?',
    highlightSpan: span('They work here?', 'They'),
    errorTags: ['missing-word'],
    correctHelper: 'do',
    healthy: 'Do they work here?',
    wordBank: ['Do', 'they', 'work', 'here', '?'],
    subject: 'they',
    baseVerb: 'work',
    explanation: 'Questions in simple present need a helper at the start. "They" + action verb → DO.',
    hint: 'Action questions start with DO or DOES.',
    tier: 'beginner', complexity: 1, grammarFocus: 'do-does',
  },
  {
    id: 'b-m2',
    sentenceType: 'negative',
    pattern: 'action',
    unhealthy: 'She not like coffee.',
    highlightSpan: span('She not like coffee.', 'She not like'),
    errorTags: ['missing-word'],
    correctHelper: 'does',
    healthy: "She doesn't like coffee.",
    acceptable: ['She does not like coffee.'],
    subject: 'she',
    baseVerb: 'like',
    explanation: 'Third person + negative action verb needs DOES (+ not). Together: doesn\'t.',
    hint: '"She / he / it" + not + action verb → doesn\'t.',
    tier: 'beginner', complexity: 2, grammarFocus: 'do-does',
  },
  {
    id: 'b-m3',
    sentenceType: 'question',
    pattern: 'action',
    unhealthy: 'He speak English?',
    highlightSpan: span('He speak English?', 'He speak'),
    errorTags: ['missing-word'],
    correctHelper: 'does',
    healthy: 'Does he speak English?',
    wordBank: ['Does', 'he', 'speak', 'English', '?'],
    subject: 'he',
    baseVerb: 'speak',
    explanation: '"He" + action verb in a question → DOES. Main verb stays in base form ("speak").',
    hint: 'Third person action question → DOES + base verb.',
    tier: 'beginner', complexity: 2, grammarFocus: 'do-does',
  },

  // ─── Extra word / verb form (3) ────────────────────────────────────────
  {
    id: 'b-e1',
    sentenceType: 'question',
    pattern: 'action',
    unhealthy: 'Does she likes pizza?',
    highlightSpan: span('Does she likes pizza?', 'likes'),
    errorTags: ['verb-form'],
    correctHelper: 'does',
    healthy: 'Does she like pizza?',
    subject: 'she',
    baseVerb: 'like',
    explanation: 'After DOES, the main verb is always base form: "like", not "likes". Only one of them carries the -s — DOES already has it.',
    hint: 'Either DOES or -s — never both.',
    tier: 'beginner', complexity: 3, grammarFocus: 'do-does',
  },
  {
    id: 'b-e2',
    sentenceType: 'question',
    pattern: 'action',
    unhealthy: 'Do he works here?',
    highlightSpan: span('Do he works here?', 'Do he works'),
    errorTags: ['wrong-helper', 'verb-form'],
    correctHelper: 'does',
    healthy: 'Does he work here?',
    subject: 'he',
    baseVerb: 'work',
    explanation: 'Two fixes: "he" needs DOES (not Do), and the main verb stays base form ("work", not "works").',
    hint: 'Third person → DOES + base verb.',
    tier: 'beginner', complexity: 4, grammarFocus: 'do-does',
  },
  {
    id: 'b-e3',
    sentenceType: 'negative',
    pattern: 'action',
    unhealthy: 'She does not likes coffee.',
    highlightSpan: span('She does not likes coffee.', 'likes'),
    errorTags: ['verb-form'],
    correctHelper: 'does',
    healthy: "She doesn't like coffee.",
    acceptable: ['She does not like coffee.'],
    subject: 'she',
    baseVerb: 'like',
    explanation: 'After DOES / DOESN\'T, the main verb stays base form. "Likes" already has the -s; you only need it once.',
    hint: 'doesn\'t + base verb (no -s on the main verb).',
    tier: 'beginner', complexity: 3, grammarFocus: 'do-does',
  },

  // ─── Short-answer contrast (2) ─────────────────────────────────────────
  {
    id: 'b-sa1',
    sentenceType: 'short-answer',
    pattern: 'action',
    unhealthy: 'Do you work here?  — Yes, I am.',
    highlightSpan: span('Do you work here?  — Yes, I am.', 'I am'),
    errorTags: ['wrong-helper'],
    correctHelper: 'do',
    healthy: 'Do you work here?  — Yes, I do.',
    subject: 'I',
    baseVerb: 'work',
    explanation: 'Short answers echo the helper from the question. "Do you…?" → "Yes, I do." / "No, I don\'t." Never mix DO with BE.',
    hint: 'Match the answer\'s helper to the question\'s helper.',
    tier: 'beginner', complexity: 3, grammarFocus: 'be-vs-do',
  },
  {
    id: 'b-sa2',
    sentenceType: 'short-answer',
    pattern: 'action',
    unhealthy: "Does she like coffee?  — No, she isn't.",
    highlightSpan: span("Does she like coffee?  — No, she isn't.", "she isn't"),
    errorTags: ['wrong-helper'],
    correctHelper: 'does',
    healthy: "Does she like coffee?  — No, she doesn't.",
    subject: 'she',
    baseVerb: 'like',
    explanation: '"Does she…?" → "Yes, she does." / "No, she doesn\'t." Use the same helper that started the question.',
    hint: 'DOES question → DOES / DOESN\'T answer.',
    tier: 'beginner', complexity: 4, grammarFocus: 'be-vs-do',
  },
];

// ============================================================================
// INTERMEDIATE (30)
// Focus: past-simple (did/was/were), present-perfect (have/has), agreement
// ============================================================================
const intermediateCases: GrammarHospitalCase[] = [
  // ─── PAST SIMPLE — did / didn't, was/were vs base (12) ────────────────
  {
    id: 'i-ps1',
    sentenceType: 'question',
    pattern: 'action',
    unhealthy: 'Did she went home early?',
    highlightSpan: span('Did she went home early?', 'went'),
    errorTags: ['verb-form'],
    correctHelper: 'did',
    healthy: 'Did she go home early?',
    subject: 'she',
    baseVerb: 'go',
    explanation: 'After DID, the main verb is always the base form: "go", not "went". DID already shows past tense.',
    hint: 'Either DID or the past form — never both.',
    tier: 'intermediate', complexity: 2, grammarFocus: 'past-simple',
  },
  {
    id: 'i-ps2',
    sentenceType: 'question',
    pattern: 'state',
    unhealthy: 'Was you tired yesterday?',
    highlightSpan: span('Was you tired yesterday?', 'Was you'),
    errorTags: ['verb-form'],
    correctHelper: 'were',
    healthy: 'Were you tired yesterday?',
    subject: 'you',
    baseVerb: 'be',
    explanation: '"You" always takes WERE in the past, even when it means one person. I/he/she/it → was · you/we/they → were.',
    hint: 'In past BE: I/he/she/it = was, you/we/they = were.',
    tier: 'intermediate', complexity: 2, grammarFocus: 'past-simple',
  },
  {
    id: 'i-ps3',
    sentenceType: 'negative',
    pattern: 'action',
    unhealthy: "He didn't went to work.",
    highlightSpan: span("He didn't went to work.", 'went'),
    errorTags: ['verb-form'],
    correctHelper: 'did',
    healthy: "He didn't go to work.",
    acceptable: ['He did not go to work.'],
    subject: 'he',
    baseVerb: 'go',
    explanation: 'After DIDN\'T, the main verb stays base form: "go". DIDN\'T already carries the past.',
    hint: "didn't + base verb (never the past form).",
    tier: 'intermediate', complexity: 2, grammarFocus: 'past-simple',
  },
  {
    id: 'i-ps4',
    sentenceType: 'question',
    pattern: 'action',
    unhealthy: 'Where you went last weekend?',
    highlightSpan: span('Where you went last weekend?', 'you went'),
    errorTags: ['missing-word', 'word-order'],
    correctHelper: 'did',
    healthy: 'Where did you go last weekend?',
    subject: 'you',
    baseVerb: 'go',
    explanation: 'Past-simple WH-questions need DID after the WH-word, and the main verb stays base form: Where + did + you + go?',
    hint: 'WH + DID + subject + base verb.',
    tier: 'intermediate', complexity: 4, grammarFocus: 'past-simple',
  },
  {
    id: 'i-ps5',
    sentenceType: 'statement',
    pattern: 'state',
    unhealthy: 'We was at the park all afternoon.',
    highlightSpan: span('We was at the park all afternoon.', 'was'),
    errorTags: ['verb-form'],
    correctHelper: 'were',
    healthy: 'We were at the park all afternoon.',
    subject: 'we',
    baseVerb: 'be',
    explanation: '"We" takes WERE in the past, never WAS. The most common slip — say it out loud a few times.',
    hint: 'we/you/they → were.',
    tier: 'intermediate', complexity: 1, grammarFocus: 'past-simple',
  },
  {
    id: 'i-ps6',
    sentenceType: 'negative',
    pattern: 'state',
    unhealthy: "They wasn't home when I called.",
    highlightSpan: span("They wasn't home when I called.", "wasn't"),
    errorTags: ['verb-form'],
    correctHelper: 'were',
    healthy: "They weren't home when I called.",
    acceptable: ['They were not home when I called.'],
    subject: 'they',
    baseVerb: 'be',
    explanation: '"They" pairs with WERE / WEREN\'T in the past. Only I/he/she/it take WASN\'T.',
    hint: "they → weren't · he/she/it → wasn't.",
    tier: 'intermediate', complexity: 2, grammarFocus: 'past-simple',
  },
  {
    id: 'i-ps7',
    sentenceType: 'question',
    pattern: 'action',
    unhealthy: 'Did they ate dinner already?',
    highlightSpan: span('Did they ate dinner already?', 'ate'),
    errorTags: ['verb-form'],
    correctHelper: 'did',
    healthy: 'Did they eat dinner already?',
    subject: 'they',
    baseVerb: 'eat',
    explanation: 'After DID, use the base form: "eat", not "ate". DID + base verb, always.',
    hint: 'DID + base verb.',
    tier: 'intermediate', complexity: 2, grammarFocus: 'past-simple',
  },
  {
    id: 'i-ps8',
    sentenceType: 'statement',
    pattern: 'action',
    unhealthy: 'I no went to the meeting.',
    highlightSpan: span('I no went to the meeting.', 'no went'),
    errorTags: ['wrong-helper'],
    correctHelper: 'did',
    healthy: "I didn't go to the meeting.",
    acceptable: ['I did not go to the meeting.'],
    subject: 'I',
    baseVerb: 'go',
    explanation: 'English doesn\'t negate verbs with "no" — use DIDN\'T + base verb in the past simple.',
    hint: "Past negative: didn't + base verb.",
    tier: 'intermediate', complexity: 3, grammarFocus: 'past-simple',
  },
  {
    id: 'i-ps9',
    sentenceType: 'negative',
    pattern: 'action',
    unhealthy: "She doesn't called me yesterday.",
    highlightSpan: span("She doesn't called me yesterday.", "doesn't called"),
    errorTags: ['wrong-helper', 'verb-form'],
    correctHelper: 'did',
    healthy: "She didn't call me yesterday.",
    acceptable: ['She did not call me yesterday.'],
    subject: 'she',
    baseVerb: 'call',
    explanation: '"Yesterday" = past, so use DIDN\'T (not doesn\'t) + base verb "call". "Doesn\'t" is for present.',
    hint: "Past time signals (yesterday, last…, ago) → didn't.",
    tier: 'intermediate', complexity: 4, grammarFocus: 'past-simple',
  },
  {
    id: 'i-ps10',
    sentenceType: 'question',
    pattern: 'action',
    unhealthy: 'Was he study last night?',
    highlightSpan: span('Was he study last night?', 'Was'),
    errorTags: ['wrong-helper'],
    correctHelper: 'did',
    healthy: 'Did he study last night?',
    acceptable: ['Was he studying last night?'],
    subject: 'he',
    baseVerb: 'study',
    explanation: 'Past simple action question → DID + base verb. "Was he study" mixes BE with a base verb — BE only works with -ing ("Was he studying?").',
    hint: 'Past action question → DID + base verb.',
    tier: 'intermediate', complexity: 4, grammarFocus: 'past-simple',
  },
  {
    id: 'i-ps11',
    sentenceType: 'short-answer',
    pattern: 'action',
    unhealthy: 'Did you finish? — Yes, I was.',
    highlightSpan: span('Did you finish? — Yes, I was.', 'I was'),
    errorTags: ['wrong-helper'],
    correctHelper: 'did',
    healthy: 'Did you finish? — Yes, I did.',
    subject: 'I',
    baseVerb: 'finish',
    explanation: 'Short answers echo the helper. "Did you…?" → "Yes, I did." / "No, I didn\'t." Don\'t switch to BE.',
    hint: 'DID question → DID answer.',
    tier: 'intermediate', complexity: 3, grammarFocus: 'past-simple',
  },
  {
    id: 'i-ps12',
    sentenceType: 'question',
    pattern: 'action',
    unhealthy: 'How long you stayed in Boston?',
    highlightSpan: span('How long you stayed in Boston?', 'you stayed'),
    errorTags: ['missing-word', 'verb-form'],
    correctHelper: 'did',
    healthy: 'How long did you stay in Boston?',
    subject: 'you',
    baseVerb: 'stay',
    explanation: 'WH + DID + subject + base verb. "How long did you stay?" — not "you stayed".',
    hint: 'WH-question past tense: WH + DID + subject + base verb.',
    tier: 'intermediate', complexity: 4, grammarFocus: 'past-simple',
  },

  // ─── PRESENT PERFECT — have / has + past participle (10) ──────────────
  {
    id: 'i-pp1',
    sentenceType: 'question',
    pattern: 'action',
    unhealthy: 'Has you seen the new movie?',
    highlightSpan: span('Has you seen the new movie?', 'Has you'),
    errorTags: ['verb-form'],
    correctHelper: 'have',
    healthy: 'Have you seen the new movie?',
    subject: 'you',
    baseVerb: 'see',
    explanation: '"You / we / they / I" → HAVE. Only "he / she / it" → HAS. (Same rule as DO / DOES.)',
    hint: 'I/you/we/they → have · he/she/it → has.',
    tier: 'intermediate', complexity: 2, grammarFocus: 'present-perfect',
  },
  {
    id: 'i-pp2',
    sentenceType: 'statement',
    pattern: 'action',
    unhealthy: 'They have went to the store already.',
    highlightSpan: span('They have went to the store already.', 'went'),
    errorTags: ['verb-form'],
    correctHelper: 'have',
    healthy: 'They have gone to the store already.',
    subject: 'they',
    baseVerb: 'go',
    explanation: 'Present perfect needs the PAST PARTICIPLE (3rd form), not the past simple. go → went → gone.',
    hint: 'have / has + past participle (gone, eaten, seen, done…).',
    tier: 'intermediate', complexity: 3, grammarFocus: 'present-perfect',
  },
  {
    id: 'i-pp3',
    sentenceType: 'negative',
    pattern: 'action',
    unhealthy: 'I have not ate breakfast yet.',
    highlightSpan: span('I have not ate breakfast yet.', 'ate'),
    errorTags: ['verb-form'],
    correctHelper: 'have',
    healthy: "I haven't eaten breakfast yet.",
    acceptable: ['I have not eaten breakfast yet.'],
    subject: 'I',
    baseVerb: 'eat',
    explanation: 'eat → ate → EATEN. Present perfect uses the past participle, not the past simple.',
    hint: 'have/has + eaten / done / been / gone / seen…',
    tier: 'intermediate', complexity: 3, grammarFocus: 'present-perfect',
  },
  {
    id: 'i-pp4',
    sentenceType: 'question',
    pattern: 'action',
    unhealthy: 'Did you ever been to Mexico?',
    highlightSpan: span('Did you ever been to Mexico?', 'Did'),
    errorTags: ['wrong-helper'],
    correctHelper: 'have',
    healthy: 'Have you ever been to Mexico?',
    subject: 'you',
    baseVerb: 'be',
    explanation: '"Ever been" needs HAVE (present perfect — any time up to now), not DID (past simple — finished time).',
    hint: '"Ever / never / already / yet" → use HAVE / HAS.',
    tier: 'intermediate', complexity: 4, grammarFocus: 'present-perfect',
  },
  {
    id: 'i-pp5',
    sentenceType: 'statement',
    pattern: 'action',
    unhealthy: 'She have lived here since 2020.',
    highlightSpan: span('She have lived here since 2020.', 'have'),
    errorTags: ['verb-form'],
    correctHelper: 'has',
    healthy: 'She has lived here since 2020.',
    subject: 'she',
    baseVerb: 'live',
    explanation: '"She" takes HAS, not HAVE. (Same third-person -s rule as the simple present.)',
    hint: 'he/she/it → has.',
    tier: 'intermediate', complexity: 2, grammarFocus: 'present-perfect',
  },
  {
    id: 'i-pp6',
    sentenceType: 'statement',
    pattern: 'action',
    unhealthy: 'I have saw that movie three times.',
    highlightSpan: span('I have saw that movie three times.', 'saw'),
    errorTags: ['verb-form'],
    correctHelper: 'have',
    healthy: 'I have seen that movie three times.',
    subject: 'I',
    baseVerb: 'see',
    explanation: 'see → saw → SEEN. Present perfect always takes the past participle.',
    hint: 'have + seen / done / been (3rd form).',
    tier: 'intermediate', complexity: 3, grammarFocus: 'present-perfect',
  },
  {
    id: 'i-pp7',
    sentenceType: 'negative',
    pattern: 'action',
    unhealthy: "He hasn't called me since two weeks.",
    highlightSpan: span("He hasn't called me since two weeks.", 'since two weeks'),
    errorTags: ['extra-word'],
    correctHelper: 'has',
    healthy: "He hasn't called me for two weeks.",
    acceptable: ["He hasn't called me in two weeks."],
    subject: 'he',
    baseVerb: 'call',
    explanation: 'Use SINCE with a starting point ("since Monday", "since 2020"). Use FOR with a length of time ("for two weeks").',
    hint: 'since + point in time · for + length of time.',
    tier: 'intermediate', complexity: 4, grammarFocus: 'present-perfect',
  },
  {
    id: 'i-pp8',
    sentenceType: 'question',
    pattern: 'action',
    unhealthy: 'How long you have studied English?',
    highlightSpan: span('How long you have studied English?', 'you have'),
    errorTags: ['word-order'],
    correctHelper: 'have',
    healthy: 'How long have you studied English?',
    subject: 'you',
    baseVerb: 'study',
    explanation: 'Questions invert the helper and subject: WH + HAVE/HAS + subject + past participle. "Have you", not "you have".',
    hint: 'Question word order: WH + HAVE + subject + verb.',
    tier: 'intermediate', complexity: 4, grammarFocus: 'present-perfect',
  },
  {
    id: 'i-pp9',
    sentenceType: 'statement',
    pattern: 'action',
    unhealthy: "We've never been in Japan.",
    highlightSpan: span("We've never been in Japan.", 'in'),
    errorTags: ['extra-word'],
    correctHelper: 'have',
    healthy: "We've never been to Japan.",
    acceptable: ['We have never been to Japan.'],
    subject: 'we',
    baseVerb: 'be',
    explanation: '"Been TO a place" is the fixed expression for "visited". "Been IN" sounds like you\'re currently inside.',
    hint: 'Been TO (a place) = visited it.',
    tier: 'intermediate', complexity: 3, grammarFocus: 'present-perfect',
  },
  {
    id: 'i-pp10',
    sentenceType: 'short-answer',
    pattern: 'action',
    unhealthy: 'Have you finished? — Yes, I did.',
    highlightSpan: span('Have you finished? — Yes, I did.', 'I did'),
    errorTags: ['wrong-helper'],
    correctHelper: 'have',
    healthy: 'Have you finished? — Yes, I have.',
    subject: 'I',
    baseVerb: 'finish',
    explanation: 'Echo the helper of the question. "Have you…?" → "Yes, I have." / "No, I haven\'t."',
    hint: 'HAVE question → HAVE answer.',
    tier: 'intermediate', complexity: 3, grammarFocus: 'present-perfect',
  },

  // ─── SUBJECT-VERB AGREEMENT (8) ────────────────────────────────────────
  {
    id: 'i-sva1',
    sentenceType: 'statement',
    pattern: 'state',
    unhealthy: 'There is many people in the waiting room.',
    highlightSpan: span('There is many people in the waiting room.', 'is'),
    errorTags: ['verb-form'],
    correctHelper: 'are',
    healthy: 'There are many people in the waiting room.',
    subject: 'many people',
    baseVerb: 'be',
    explanation: 'With "there is / there are", the verb matches what comes after. "Many people" is plural → ARE.',
    hint: 'there is + singular · there are + plural.',
    tier: 'intermediate', complexity: 2, grammarFocus: 'subject-verb-agreement',
  },
  {
    id: 'i-sva2',
    sentenceType: 'statement',
    pattern: 'action',
    unhealthy: 'Each of the students have a textbook.',
    highlightSpan: span('Each of the students have a textbook.', 'have'),
    errorTags: ['verb-form'],
    correctHelper: 'has',
    healthy: 'Each of the students has a textbook.',
    subject: 'each',
    baseVerb: 'have',
    explanation: '"Each of …" is singular — it means "every one, individually". So the verb takes -s: HAS, not HAVE.',
    hint: 'each of / one of / every one of → singular verb.',
    tier: 'intermediate', complexity: 4, grammarFocus: 'subject-verb-agreement',
  },
  {
    id: 'i-sva3',
    sentenceType: 'statement',
    pattern: 'state',
    unhealthy: 'My family are very supportive.',
    highlightSpan: span('My family are very supportive.', 'are'),
    errorTags: ['verb-form'],
    correctHelper: 'is',
    healthy: 'My family is very supportive.',
    acceptable: ['My family are very supportive.'],
    subject: 'my family',
    baseVerb: 'be',
    explanation: 'In American English, collective nouns like "family", "team", "staff" usually take a singular verb (IS). British English allows ARE when emphasizing individuals.',
    hint: 'In US English: family / team / staff → singular.',
    tier: 'intermediate', complexity: 4, grammarFocus: 'subject-verb-agreement',
  },
  {
    id: 'i-sva4',
    sentenceType: 'statement',
    pattern: 'action',
    unhealthy: 'My brother and his wife works at the same hospital.',
    highlightSpan: span('My brother and his wife works at the same hospital.', 'works'),
    errorTags: ['verb-form'],
    correctHelper: 'do',
    healthy: 'My brother and his wife work at the same hospital.',
    subject: 'my brother and his wife',
    baseVerb: 'work',
    explanation: 'Two subjects joined by AND make a plural — drop the -s. "Brother AND wife" → WORK, not WORKS.',
    hint: 'X and Y → plural verb (no -s).',
    tier: 'intermediate', complexity: 3, grammarFocus: 'subject-verb-agreement',
  },
  {
    id: 'i-sva5',
    sentenceType: 'statement',
    pattern: 'state',
    unhealthy: 'None of the answers are correct.',
    highlightSpan: span('None of the answers are correct.', 'are'),
    errorTags: ['verb-form'],
    correctHelper: 'is',
    healthy: 'None of the answers is correct.',
    acceptable: ['None of the answers are correct.'],
    subject: 'none',
    baseVerb: 'be',
    explanation: 'Strictly, "none = not one" → singular IS. In everyday usage ARE is widely accepted; we accept both, but the formal answer is IS.',
    hint: 'none = not one → singular (formal).',
    tier: 'intermediate', complexity: 5, grammarFocus: 'subject-verb-agreement',
  },
  {
    id: 'i-sva6',
    sentenceType: 'question',
    pattern: 'action',
    unhealthy: 'Do everyone understand the homework?',
    highlightSpan: span('Do everyone understand the homework?', 'Do'),
    errorTags: ['wrong-helper'],
    correctHelper: 'does',
    healthy: 'Does everyone understand the homework?',
    subject: 'everyone',
    baseVerb: 'understand',
    explanation: '"Everyone / someone / nobody / each" are SINGULAR even though they feel like groups. → DOES.',
    hint: 'everyone / nobody / someone → singular → DOES.',
    tier: 'intermediate', complexity: 3, grammarFocus: 'subject-verb-agreement',
  },
  {
    id: 'i-sva7',
    sentenceType: 'statement',
    pattern: 'action',
    unhealthy: 'The list of supplies are on the table.',
    highlightSpan: span('The list of supplies are on the table.', 'are'),
    errorTags: ['verb-form'],
    correctHelper: 'is',
    healthy: 'The list of supplies is on the table.',
    subject: 'the list',
    baseVerb: 'be',
    explanation: 'The real subject is "the list" (singular) — "of supplies" is just a prepositional phrase. → IS.',
    hint: 'Find the head noun, not the noun inside "of …".',
    tier: 'intermediate', complexity: 5, grammarFocus: 'subject-verb-agreement',
  },
  {
    id: 'i-sva8',
    sentenceType: 'statement',
    pattern: 'action',
    unhealthy: 'Either John or his sisters drives to the airport.',
    highlightSpan: span('Either John or his sisters drives to the airport.', 'drives'),
    errorTags: ['verb-form'],
    correctHelper: 'do',
    healthy: 'Either John or his sisters drive to the airport.',
    subject: 'either … or …',
    baseVerb: 'drive',
    explanation: 'With "either … or …", the verb agrees with the NEAREST subject. "His sisters" is plural and closest → DRIVE.',
    hint: 'either / neither … or / nor: agree with the nearest subject.',
    tier: 'intermediate', complexity: 5, grammarFocus: 'subject-verb-agreement',
  },
];

// ============================================================================
// ADVANCED (35)
// Focus: modals, embedded questions, question tags, mixed-helper traps
// ============================================================================
const advancedCases: GrammarHospitalCase[] = [
  // ─── MODALS — can / could / should / would / will (10) ─────────────────
  {
    id: 'a-m1',
    sentenceType: 'question',
    pattern: 'action',
    unhealthy: 'Do you can help me with this?',
    highlightSpan: span('Do you can help me with this?', 'Do'),
    errorTags: ['extra-word', 'wrong-helper'],
    correctHelper: 'can',
    healthy: 'Can you help me with this?',
    subject: 'you',
    baseVerb: 'help',
    explanation: 'Modals (can / could / should / would / will / may / might) ARE the helper. Don\'t add DO/DOES/DID in front. Just invert: CAN + subject + base verb.',
    hint: 'Modal questions: MODAL + subject + base verb. No DO needed.',
    tier: 'advanced', complexity: 2, grammarFocus: 'modals',
  },
  {
    id: 'a-m2',
    sentenceType: 'statement',
    pattern: 'action',
    unhealthy: 'She can to drive a manual car.',
    highlightSpan: span('She can to drive a manual car.', 'to drive'),
    errorTags: ['extra-word'],
    correctHelper: 'can',
    healthy: 'She can drive a manual car.',
    subject: 'she',
    baseVerb: 'drive',
    explanation: 'No "to" after a modal — ever. MODAL + base verb directly: can drive, should go, would help.',
    hint: 'Modal + base verb (NO "to" between).',
    tier: 'advanced', complexity: 2, grammarFocus: 'modals',
  },
  {
    id: 'a-m3',
    sentenceType: 'negative',
    pattern: 'action',
    unhealthy: "He shouldn't to smoke in the building.",
    highlightSpan: span("He shouldn't to smoke in the building.", 'to smoke'),
    errorTags: ['extra-word'],
    correctHelper: 'should',
    healthy: "He shouldn't smoke in the building.",
    acceptable: ['He should not smoke in the building.'],
    subject: 'he',
    baseVerb: 'smoke',
    explanation: 'Same rule with the negative: "shouldn\'t smoke" — never "shouldn\'t TO smoke".',
    hint: "Modal + base verb (also for shouldn't, can't, wouldn't…).",
    tier: 'advanced', complexity: 2, grammarFocus: 'modals',
  },
  {
    id: 'a-m4',
    sentenceType: 'statement',
    pattern: 'action',
    unhealthy: 'I would helping you, but I am busy.',
    highlightSpan: span('I would helping you, but I am busy.', 'helping'),
    errorTags: ['verb-form'],
    correctHelper: 'would',
    healthy: 'I would help you, but I am busy.',
    subject: 'I',
    baseVerb: 'help',
    explanation: 'Modals always take the BASE form, never -ing. "Would help", not "would helping".',
    hint: 'Modal + base verb (not -ing, not past).',
    tier: 'advanced', complexity: 3, grammarFocus: 'modals',
  },
  {
    id: 'a-m5',
    sentenceType: 'question',
    pattern: 'action',
    unhealthy: 'Can he speaks four languages?',
    highlightSpan: span('Can he speaks four languages?', 'speaks'),
    errorTags: ['verb-form'],
    correctHelper: 'can',
    healthy: 'Can he speak four languages?',
    subject: 'he',
    baseVerb: 'speak',
    explanation: 'Even with "he / she / it", the verb after a modal stays base form — no -s. "Can he speak", not "speaks".',
    hint: 'Modal + base verb (no -s, ever).',
    tier: 'advanced', complexity: 3, grammarFocus: 'modals',
  },
  {
    id: 'a-m6',
    sentenceType: 'statement',
    pattern: 'action',
    unhealthy: 'You must to wear a mask in the hospital.',
    highlightSpan: span('You must to wear a mask in the hospital.', 'to wear'),
    errorTags: ['extra-word'],
    correctHelper: 'should',
    healthy: 'You must wear a mask in the hospital.',
    subject: 'you',
    baseVerb: 'wear',
    explanation: '"Must" is a modal — no "to". (Note: "have to" needs "to", but "must" does not.)',
    hint: 'must + base verb · have + TO + base verb (different rules).',
    tier: 'advanced', complexity: 4, grammarFocus: 'modals',
  },
  {
    id: 'a-m7',
    sentenceType: 'negative',
    pattern: 'action',
    unhealthy: "I don't can swim very well.",
    highlightSpan: span("I don't can swim very well.", "don't can"),
    errorTags: ['wrong-helper', 'extra-word'],
    correctHelper: 'can',
    healthy: "I can't swim very well.",
    acceptable: ['I cannot swim very well.'],
    subject: 'I',
    baseVerb: 'swim',
    explanation: 'Modals negate themselves directly: CAN → CAN\'T. Don\'t use DO/DON\'T with a modal — the modal already does that job.',
    hint: "Modal negative: can't / shouldn't / wouldn't. No DO needed.",
    tier: 'advanced', complexity: 3, grammarFocus: 'modals',
  },
  {
    id: 'a-m8',
    sentenceType: 'question',
    pattern: 'action',
    unhealthy: 'What should I to do?',
    highlightSpan: span('What should I to do?', 'to do'),
    errorTags: ['extra-word'],
    correctHelper: 'should',
    healthy: 'What should I do?',
    subject: 'I',
    baseVerb: 'do',
    explanation: 'Same rule even in a WH-question: modal + base verb, no "to". "What should I do?"',
    hint: 'WH + modal + subject + base verb.',
    tier: 'advanced', complexity: 3, grammarFocus: 'modals',
  },
  {
    id: 'a-m9',
    sentenceType: 'statement',
    pattern: 'action',
    unhealthy: 'When I was young, I could to run very fast.',
    highlightSpan: span('When I was young, I could to run very fast.', 'to run'),
    errorTags: ['extra-word'],
    correctHelper: 'could',
    healthy: 'When I was young, I could run very fast.',
    subject: 'I',
    baseVerb: 'run',
    explanation: 'Past modal still no "to": COULD + base verb. "Could run", "would help", "should know".',
    hint: 'All modals (past or present): + base verb, no "to".',
    tier: 'advanced', complexity: 3, grammarFocus: 'modals',
  },
  {
    id: 'a-m10',
    sentenceType: 'question',
    pattern: 'action',
    unhealthy: 'Would you to like some coffee?',
    highlightSpan: span('Would you to like some coffee?', 'you to like'),
    errorTags: ['extra-word', 'word-order'],
    correctHelper: 'would',
    healthy: 'Would you like some coffee?',
    subject: 'you',
    baseVerb: 'like',
    explanation: '"Would you like…?" is fixed — no "to". The modal WOULD + base verb LIKE, in that order.',
    hint: '"Would you like…?" — the polite offer pattern.',
    tier: 'advanced', complexity: 4, grammarFocus: 'modals',
  },

  // ─── EMBEDDED QUESTIONS (10) ──────────────────────────────────────────
  {
    id: 'a-eq1',
    sentenceType: 'question',
    pattern: 'action',
    unhealthy: 'Do you know does she work here?',
    highlightSpan: span('Do you know does she work here?', 'does she'),
    errorTags: ['extra-word', 'word-order'],
    correctHelper: 'do',
    healthy: 'Do you know if she works here?',
    acceptable: ['Do you know whether she works here?'],
    subject: 'you',
    baseVerb: 'know',
    explanation: 'Inside an embedded (indirect) question, drop the question helper. Use IF/WHETHER + subject + verb in normal statement order: "if she works here".',
    hint: 'Embedded yes/no questions: IF + subject + verb (no DO/DOES).',
    tier: 'advanced', complexity: 4, grammarFocus: 'embedded-question',
  },
  {
    id: 'a-eq2',
    sentenceType: 'question',
    pattern: 'action',
    unhealthy: 'Can you tell me where do they live?',
    highlightSpan: span('Can you tell me where do they live?', 'do they'),
    errorTags: ['extra-word', 'word-order'],
    correctHelper: 'can',
    healthy: 'Can you tell me where they live?',
    subject: 'you',
    baseVerb: 'tell',
    explanation: 'Inside an embedded WH-question, no DO and no inversion. Just: WH + subject + verb. "Where they live."',
    hint: 'Embedded WH-questions: WH + subject + verb. No helper, no flip.',
    tier: 'advanced', complexity: 4, grammarFocus: 'embedded-question',
  },
  {
    id: 'a-eq3',
    sentenceType: 'statement',
    pattern: 'action',
    unhealthy: "I don't know what is her name.",
    highlightSpan: span("I don't know what is her name.", 'is her name'),
    errorTags: ['word-order'],
    correctHelper: 'do',
    healthy: "I don't know what her name is.",
    subject: 'I',
    baseVerb: 'know',
    explanation: 'Inside the embedded question, put the verb LAST: "what her name IS", not "what IS her name".',
    hint: 'Embedded question: subject before the verb (statement order).',
    tier: 'advanced', complexity: 4, grammarFocus: 'embedded-question',
  },
  {
    id: 'a-eq4',
    sentenceType: 'question',
    pattern: 'action',
    unhealthy: 'Do you know when does the store close?',
    highlightSpan: span('Do you know when does the store close?', 'does the store'),
    errorTags: ['extra-word', 'word-order'],
    correctHelper: 'do',
    healthy: 'Do you know when the store closes?',
    subject: 'you',
    baseVerb: 'know',
    explanation: 'Embedded WH-question → drop the DOES and bring back the -s on the verb: "when the store closes".',
    hint: 'Embedded: WH + subject + verb (with normal -s if needed).',
    tier: 'advanced', complexity: 5, grammarFocus: 'embedded-question',
  },
  {
    id: 'a-eq5',
    sentenceType: 'statement',
    pattern: 'action',
    unhealthy: "I'm not sure if can she come tomorrow.",
    highlightSpan: span("I'm not sure if can she come tomorrow.", 'can she'),
    errorTags: ['word-order'],
    correctHelper: 'can',
    healthy: "I'm not sure if she can come tomorrow.",
    subject: 'I',
    baseVerb: 'be',
    explanation: 'Even with a modal, inside the embedded clause use statement order: subject BEFORE the modal. "If she can come", not "if can she come".',
    hint: 'Embedded clause: subject + modal + verb.',
    tier: 'advanced', complexity: 4, grammarFocus: 'embedded-question',
  },
  {
    id: 'a-eq6',
    sentenceType: 'question',
    pattern: 'action',
    unhealthy: 'Could you tell me what time is it?',
    highlightSpan: span('Could you tell me what time is it?', 'is it'),
    errorTags: ['word-order'],
    correctHelper: 'could',
    healthy: 'Could you tell me what time it is?',
    subject: 'you',
    baseVerb: 'tell',
    explanation: 'Polite request → embedded question. "What time IT IS", not "what time IS IT".',
    hint: 'Polite asks: subject before the verb in the embedded part.',
    tier: 'advanced', complexity: 4, grammarFocus: 'embedded-question',
  },
  {
    id: 'a-eq7',
    sentenceType: 'statement',
    pattern: 'action',
    unhealthy: 'She asked me where did I go to school.',
    highlightSpan: span('She asked me where did I go to school.', 'did I'),
    errorTags: ['extra-word', 'word-order'],
    correctHelper: 'do',
    healthy: 'She asked me where I went to school.',
    subject: 'she',
    baseVerb: 'ask',
    explanation: 'Reported / embedded questions drop DID. The verb shifts to the past form directly: "where I WENT to school".',
    hint: 'Reported question: drop the helper, shift the verb to the past.',
    tier: 'advanced', complexity: 5, grammarFocus: 'embedded-question',
  },
  {
    id: 'a-eq8',
    sentenceType: 'question',
    pattern: 'action',
    unhealthy: 'Do you know how much does it cost?',
    highlightSpan: span('Do you know how much does it cost?', 'does it'),
    errorTags: ['extra-word', 'word-order'],
    correctHelper: 'do',
    healthy: 'Do you know how much it costs?',
    subject: 'you',
    baseVerb: 'know',
    explanation: 'Embedded WH: drop DOES, restore the -s on COST. "How much it COSTS."',
    hint: 'Embedded: WH + subject + verb (+ -s for he/she/it).',
    tier: 'advanced', complexity: 5, grammarFocus: 'embedded-question',
  },
  {
    id: 'a-eq9',
    sentenceType: 'statement',
    pattern: 'action',
    unhealthy: "I wonder why is he always late.",
    highlightSpan: span("I wonder why is he always late.", 'is he'),
    errorTags: ['word-order'],
    correctHelper: 'do',
    healthy: 'I wonder why he is always late.',
    subject: 'I',
    baseVerb: 'wonder',
    explanation: 'After "I wonder…" you have an embedded question — subject first: "why HE IS always late".',
    hint: 'After "wonder / not sure / know / ask": subject + verb.',
    tier: 'advanced', complexity: 4, grammarFocus: 'embedded-question',
  },
  {
    id: 'a-eq10',
    sentenceType: 'question',
    pattern: 'action',
    unhealthy: 'Can you tell me where is the bathroom?',
    highlightSpan: span('Can you tell me where is the bathroom?', 'is the bathroom'),
    errorTags: ['word-order'],
    correctHelper: 'can',
    healthy: 'Can you tell me where the bathroom is?',
    subject: 'you',
    baseVerb: 'tell',
    explanation: 'Classic polite request error. "Where the bathroom IS" — subject before BE.',
    hint: 'Polite request → embedded question → subject + verb order.',
    tier: 'advanced', complexity: 4, grammarFocus: 'embedded-question',
  },

  // ─── QUESTION TAGS (8) ─────────────────────────────────────────────────
  {
    id: 'a-qt1',
    sentenceType: 'short-answer',
    pattern: 'state',
    unhealthy: "She works here, isn't she?",
    highlightSpan: span("She works here, isn't she?", "isn't"),
    errorTags: ['wrong-helper'],
    correctHelper: 'does',
    healthy: "She works here, doesn't she?",
    subject: 'she',
    baseVerb: 'work',
    explanation: 'The tag mirrors the helper of the main verb. "Works" is simple present action → tag is DOESN\'T. Use BE\'s tag only when the main verb is BE.',
    hint: 'Tag mirrors the helper: WORKS → doesn\'t · IS → isn\'t.',
    tier: 'advanced', complexity: 3, grammarFocus: 'question-tag',
  },
  {
    id: 'a-qt2',
    sentenceType: 'short-answer',
    pattern: 'action',
    unhealthy: "They don't smoke, doesn't they?",
    highlightSpan: span("They don't smoke, doesn't they?", "doesn't they"),
    errorTags: ['verb-form'],
    correctHelper: 'do',
    healthy: "They don't smoke, do they?",
    subject: 'they',
    baseVerb: 'smoke',
    explanation: 'Two rules: (1) negative main → POSITIVE tag, so "don\'t" → "do". (2) "they" → DO, not DOES.',
    hint: 'Negative sentence → positive tag (and vice versa). Match the subject.',
    tier: 'advanced', complexity: 4, grammarFocus: 'question-tag',
  },
  {
    id: 'a-qt3',
    sentenceType: 'short-answer',
    pattern: 'state',
    unhealthy: "You're tired, are you?",
    highlightSpan: span("You're tired, are you?", 'are'),
    errorTags: ['wrong-helper'],
    correctHelper: 'are',
    healthy: "You're tired, aren't you?",
    subject: 'you',
    baseVerb: 'be',
    explanation: 'Positive main ("you\'re tired") → NEGATIVE tag ("aren\'t you"). Same helper, opposite polarity.',
    hint: 'Positive sentence → negative tag.',
    tier: 'advanced', complexity: 3, grammarFocus: 'question-tag',
  },
  {
    id: 'a-qt4',
    sentenceType: 'short-answer',
    pattern: 'action',
    unhealthy: "He went to the meeting, didn't he go?",
    highlightSpan: span("He went to the meeting, didn't he go?", "didn't he go"),
    errorTags: ['extra-word'],
    correctHelper: 'did',
    healthy: "He went to the meeting, didn't he?",
    subject: 'he',
    baseVerb: 'go',
    explanation: 'Tag = helper + pronoun only. No main verb in the tag. "Didn\'t he?", not "Didn\'t he go?".',
    hint: 'Tag is just: helper + pronoun. Nothing else.',
    tier: 'advanced', complexity: 4, grammarFocus: 'question-tag',
  },
  {
    id: 'a-qt5',
    sentenceType: 'short-answer',
    pattern: 'action',
    unhealthy: "She can drive, can't her?",
    highlightSpan: span("She can drive, can't her?", 'her'),
    errorTags: ['verb-form'],
    correctHelper: 'can',
    healthy: "She can drive, can't she?",
    subject: 'she',
    baseVerb: 'drive',
    explanation: 'Tag pronouns are always subject pronouns: SHE, HE, THEY, IT — never her / him / them.',
    hint: 'Tag pronoun: she / he / they / it (subject form).',
    tier: 'advanced', complexity: 4, grammarFocus: 'question-tag',
  },
  {
    id: 'a-qt6',
    sentenceType: 'short-answer',
    pattern: 'action',
    unhealthy: "Let's go to the park, shall we go?",
    highlightSpan: span("Let's go to the park, shall we go?", 'shall we go'),
    errorTags: ['extra-word'],
    correctHelper: 'will',
    healthy: "Let's go to the park, shall we?",
    subject: 'we',
    baseVerb: 'go',
    explanation: 'After "Let\'s …", the fixed tag is "shall we?" — pronoun only, no main verb repeated.',
    hint: 'Let\'s … → "shall we?" (fixed).',
    tier: 'advanced', complexity: 5, grammarFocus: 'question-tag',
  },
  {
    id: 'a-qt7',
    sentenceType: 'short-answer',
    pattern: 'action',
    unhealthy: "You haven't eaten yet, have you eaten?",
    highlightSpan: span("You haven't eaten yet, have you eaten?", 'have you eaten'),
    errorTags: ['extra-word'],
    correctHelper: 'have',
    healthy: "You haven't eaten yet, have you?",
    subject: 'you',
    baseVerb: 'eat',
    explanation: 'Negative present perfect → positive tag with HAVE + pronoun. Don\'t repeat the past participle.',
    hint: 'Present perfect tag: have/has + pronoun.',
    tier: 'advanced', complexity: 4, grammarFocus: 'question-tag',
  },
  {
    id: 'a-qt8',
    sentenceType: 'short-answer',
    pattern: 'action',
    unhealthy: "I'm late, am I not?",
    highlightSpan: span("I'm late, am I not?", 'am I not'),
    errorTags: ['verb-form'],
    correctHelper: 'am',
    healthy: "I'm late, aren't I?",
    acceptable: ["I'm late, am I not?"],
    subject: 'I',
    baseVerb: 'be',
    explanation: 'The conversational tag for "I am" is the irregular "aren\'t I?" — even though "am I not?" is technically correct, no one says it.',
    hint: '"I am" → tag is "aren\'t I?" (one of English\'s quirks).',
    tier: 'advanced', complexity: 5, grammarFocus: 'question-tag',
  },

  // ─── PAST PERFECT — had vs. has/have (8) ───────────────────────────────
  // Past perfect = HAD + past participle, for an action that happened BEFORE
  // another past moment. Adult learners constantly swap HAD with HAS / HAVE
  // because the contractions ('d / 's / 've) sound alike in fast speech.
  {
    id: 'a-pp1',
    sentenceType: 'statement',
    pattern: 'action',
    unhealthy: 'By the time I arrived, the movie has already started.',
    highlightSpan: span('By the time I arrived, the movie has already started.', 'has'),
    errorTags: ['wrong-helper'],
    correctHelper: 'had',
    healthy: 'By the time I arrived, the movie had already started.',
    subject: 'the movie',
    baseVerb: 'start',
    explanation: 'Two past moments: I arrived (past simple) and — before that — the movie started. Use HAD for the earlier one: "had already started." HAS is for present perfect (connecting to now).',
    hint: 'Two past actions, one before the other → HAD + past participle for the earlier one.',
    tier: 'advanced', complexity: 3, grammarFocus: 'past-perfect',
  },
  {
    id: 'a-pp2',
    sentenceType: 'statement',
    pattern: 'action',
    unhealthy: 'When the police arrived, the thief have already escaped.',
    highlightSpan: span('When the police arrived, the thief have already escaped.', 'have'),
    errorTags: ['wrong-helper'],
    correctHelper: 'had',
    healthy: 'When the police arrived, the thief had already escaped.',
    subject: 'the thief',
    baseVerb: 'escape',
    explanation: 'The escape happened BEFORE the police arrived — both in the past. → HAD escaped. HAVE would connect the action to right now, which doesn\'t fit.',
    hint: 'Earlier-of-two-past-events → HAD (not have / has).',
    tier: 'advanced', complexity: 3, grammarFocus: 'past-perfect',
  },
  {
    id: 'a-pp3',
    sentenceType: 'statement',
    pattern: 'action',
    unhealthy: 'She had ate dinner before I called.',
    highlightSpan: span('She had ate dinner before I called.', 'ate'),
    errorTags: ['verb-form'],
    correctHelper: 'had',
    healthy: 'She had eaten dinner before I called.',
    subject: 'she',
    baseVerb: 'eat',
    explanation: 'HAD is right (it happened before I called), but the verb must be the PAST PARTICIPLE: eat → ate → EATEN. So: "had eaten."',
    hint: 'had + past participle (eaten, gone, seen, done, written…).',
    tier: 'advanced', complexity: 3, grammarFocus: 'past-perfect',
  },
  {
    id: 'a-pp4',
    sentenceType: 'statement',
    pattern: 'action',
    unhealthy: "He has lived in Boston for 5 years before he moved to Texas.",
    highlightSpan: span("He has lived in Boston for 5 years before he moved to Texas.", 'has lived'),
    errorTags: ['wrong-helper'],
    correctHelper: 'had',
    healthy: 'He had lived in Boston for 5 years before he moved to Texas.',
    subject: 'he',
    baseVerb: 'live',
    explanation: '"He moved" is past, so the 5 years happened even earlier in the past → HAD lived. Use HAS for things still true now: "He has lived here for 5 years (and still does)."',
    hint: 'If the second action is past, the first one goes one more step back → HAD.',
    tier: 'advanced', complexity: 4, grammarFocus: 'past-perfect',
  },
  {
    id: 'a-pp5',
    sentenceType: 'question',
    pattern: 'action',
    unhealthy: 'Has you finished the project when the boss called?',
    highlightSpan: span('Has you finished the project when the boss called?', 'Has you'),
    errorTags: ['wrong-helper', 'verb-form'],
    correctHelper: 'had',
    healthy: 'Had you finished the project when the boss called?',
    subject: 'you',
    baseVerb: 'finish',
    explanation: 'Two things to fix: it should be HAD (past perfect — finished BEFORE the call), and even if it were present perfect, "you" takes HAVE, not HAS.',
    hint: 'Past perfect question: HAD + subject + past participle.',
    tier: 'advanced', complexity: 5, grammarFocus: 'past-perfect',
  },
  {
    id: 'a-pp6',
    sentenceType: 'negative',
    pattern: 'action',
    unhealthy: "I haven't seen that movie before last weekend.",
    highlightSpan: span("I haven't seen that movie before last weekend.", "haven't"),
    errorTags: ['wrong-helper'],
    correctHelper: 'had',
    healthy: "I hadn't seen that movie before last weekend.",
    acceptable: ['I had not seen that movie before last weekend.'],
    subject: 'I',
    baseVerb: 'see',
    explanation: '"Before last weekend" sets a past reference point, so the not-seeing happened even earlier → HADN\'T. HAVEN\'T would connect the action to right now.',
    hint: 'before / by + a past time → HADN\'T (not haven\'t).',
    tier: 'advanced', complexity: 4, grammarFocus: 'past-perfect',
  },
  {
    id: 'a-pp7',
    sentenceType: 'statement',
    pattern: 'action',
    unhealthy: "If I had knew, I would have called you.",
    highlightSpan: span("If I had knew, I would have called you.", 'knew'),
    errorTags: ['verb-form'],
    correctHelper: 'had',
    healthy: 'If I had known, I would have called you.',
    subject: 'I',
    baseVerb: 'know',
    explanation: 'Third conditional uses HAD + past participle, not past simple. know → knew → KNOWN. "If I had KNOWN…"',
    hint: '3rd conditional: IF + HAD + past participle, WOULD HAVE + past participle.',
    tier: 'advanced', complexity: 5, grammarFocus: 'past-perfect',
  },
  {
    id: 'a-pp8',
    sentenceType: 'statement',
    pattern: 'action',
    unhealthy: "We've never been to Mexico until last summer.",
    highlightSpan: span("We've never been to Mexico until last summer.", "We've"),
    errorTags: ['wrong-helper'],
    correctHelper: 'had',
    healthy: "We'd never been to Mexico until last summer.",
    acceptable: ['We had never been to Mexico until last summer.'],
    subject: 'we',
    baseVerb: 'be',
    explanation: '"Until last summer" sets a past boundary — the never-been was true up to that past point. → HAD never been ("we\'d"). "\'ve" (have) would mean still never been now.',
    hint: "until + past time → 'd never (had), not 've never (have).",
    tier: 'advanced', complexity: 5, grammarFocus: 'past-perfect',
  },

  // ─── FUTURE SIMPLE — will / won't + base verb (8) ─────────────────────
  // Will is a modal: same rules as can/should/would. No "to", no -ing, no -s.
  {
    id: 'a-fs1',
    sentenceType: 'question',
    pattern: 'action',
    unhealthy: 'Do you will come to the party?',
    highlightSpan: span('Do you will come to the party?', 'Do'),
    errorTags: ['extra-word', 'wrong-helper'],
    correctHelper: 'will',
    healthy: 'Will you come to the party?',
    subject: 'you',
    baseVerb: 'come',
    explanation: 'WILL is a modal — it IS the question helper. Don\'t add DO. Just invert: WILL + subject + base verb.',
    hint: 'Future question: WILL + subject + base verb. No DO.',
    tier: 'advanced', complexity: 2, grammarFocus: 'future-simple',
  },
  {
    id: 'a-fs2',
    sentenceType: 'statement',
    pattern: 'action',
    unhealthy: 'I will to call you tomorrow.',
    highlightSpan: span('I will to call you tomorrow.', 'to call'),
    errorTags: ['extra-word'],
    correctHelper: 'will',
    healthy: 'I will call you tomorrow.',
    subject: 'I',
    baseVerb: 'call',
    explanation: 'No "to" after a modal. WILL + base verb directly: "will call", "will go", "will see".',
    hint: 'Modal + base verb (no "to" between).',
    tier: 'advanced', complexity: 1, grammarFocus: 'future-simple',
  },
  {
    id: 'a-fs3',
    sentenceType: 'statement',
    pattern: 'action',
    unhealthy: 'She will going to the doctor next week.',
    highlightSpan: span('She will going to the doctor next week.', 'will going'),
    errorTags: ['verb-form'],
    correctHelper: 'will',
    healthy: 'She will go to the doctor next week.',
    acceptable: ['She is going to the doctor next week.'],
    subject: 'she',
    baseVerb: 'go',
    explanation: 'After WILL, the verb is BASE form, never -ing. (You may be thinking of "is going to", which is a different future form.)',
    hint: 'will + base verb · BE + going to + base verb (two different futures).',
    tier: 'advanced', complexity: 3, grammarFocus: 'future-simple',
  },
  {
    id: 'a-fs4',
    sentenceType: 'negative',
    pattern: 'action',
    unhealthy: "He don't will help us move.",
    highlightSpan: span("He don't will help us move.", "don't will"),
    errorTags: ['wrong-helper', 'extra-word'],
    correctHelper: 'will',
    healthy: "He won't help us move.",
    acceptable: ['He will not help us move.'],
    subject: 'he',
    baseVerb: 'help',
    explanation: 'WILL negates itself: WILL NOT → WON\'T. Don\'t use DON\'T with a modal — the modal already does that job.',
    hint: "Future negative: won't / will not (no don't / doesn't).",
    tier: 'advanced', complexity: 3, grammarFocus: 'future-simple',
  },
  {
    id: 'a-fs5',
    sentenceType: 'statement',
    pattern: 'action',
    unhealthy: 'It will rains tomorrow.',
    highlightSpan: span('It will rains tomorrow.', 'rains'),
    errorTags: ['verb-form'],
    correctHelper: 'will',
    healthy: 'It will rain tomorrow.',
    subject: 'it',
    baseVerb: 'rain',
    explanation: 'After WILL, no -s — ever. "Will rain", not "will rains". Modals always take the base form.',
    hint: 'Modal + base verb (no -s, even with he/she/it).',
    tier: 'advanced', complexity: 2, grammarFocus: 'future-simple',
  },
  {
    id: 'a-fs6',
    sentenceType: 'short-answer',
    pattern: 'action',
    unhealthy: 'Will you be at the meeting? — Yes, I do.',
    highlightSpan: span('Will you be at the meeting? — Yes, I do.', 'I do'),
    errorTags: ['wrong-helper'],
    correctHelper: 'will',
    healthy: 'Will you be at the meeting? — Yes, I will.',
    subject: 'I',
    baseVerb: 'be',
    explanation: 'Short answers echo the question helper. "Will you…?" → "Yes, I will." / "No, I won\'t." Never swap to DO.',
    hint: 'WILL question → WILL / WON\'T answer.',
    tier: 'advanced', complexity: 3, grammarFocus: 'future-simple',
  },
  {
    id: 'a-fs7',
    sentenceType: 'question',
    pattern: 'action',
    unhealthy: 'What time will you arriving?',
    highlightSpan: span('What time will you arriving?', 'arriving'),
    errorTags: ['verb-form'],
    correctHelper: 'will',
    healthy: 'What time will you arrive?',
    subject: 'you',
    baseVerb: 'arrive',
    explanation: 'WH + WILL + subject + base verb. "Will you arrive" — not "arriving". The -ing form belongs to continuous tenses, not WILL.',
    hint: 'WH-future: WH + WILL + subject + base verb.',
    tier: 'advanced', complexity: 3, grammarFocus: 'future-simple',
  },
  {
    id: 'a-fs8',
    sentenceType: 'statement',
    pattern: 'action',
    unhealthy: 'If it will rain, we will cancel the picnic.',
    highlightSpan: span('If it will rain, we will cancel the picnic.', 'will rain'),
    errorTags: ['wrong-helper'],
    correctHelper: 'will',
    healthy: 'If it rains, we will cancel the picnic.',
    subject: 'we',
    baseVerb: 'cancel',
    explanation: 'First conditional: IF + present simple, WILL + base verb. No "will" inside the IF clause.',
    hint: '1st conditional: IF + present, WILL + base. (Never "if + will".)',
    tier: 'advanced', complexity: 4, grammarFocus: 'future-simple',
  },

  // ─── FUTURE PERFECT — will have + past participle (6) ─────────────────
  // For something completed BEFORE a future moment. The trap: confusing
  // "will have" (future perfect) with "have" (present perfect) or "will be"
  // (future continuous).
  {
    id: 'a-fp1',
    sentenceType: 'statement',
    pattern: 'action',
    unhealthy: 'By next June, I will graduate from nursing school.',
    highlightSpan: span('By next June, I will graduate from nursing school.', 'will graduate'),
    errorTags: ['missing-word'],
    correctHelper: 'will',
    healthy: 'By next June, I will have graduated from nursing school.',
    subject: 'I',
    baseVerb: 'graduate',
    explanation: '"By + future time" → use future perfect: WILL HAVE + past participle. It says the action will be finished before that point.',
    hint: 'by + future time → will have + past participle.',
    tier: 'advanced', complexity: 4, grammarFocus: 'future-perfect',
  },
  {
    id: 'a-fp2',
    sentenceType: 'statement',
    pattern: 'action',
    unhealthy: 'By the time you arrive, I will has finished cooking.',
    highlightSpan: span('By the time you arrive, I will has finished cooking.', 'will has'),
    errorTags: ['verb-form'],
    correctHelper: 'will',
    healthy: 'By the time you arrive, I will have finished cooking.',
    subject: 'I',
    baseVerb: 'finish',
    explanation: 'After WILL, always HAVE — never HAS. Modals don\'t take -s, even with he/she/it. "Will have finished", not "will has".',
    hint: 'WILL HAVE + past participle (always have, never has).',
    tier: 'advanced', complexity: 3, grammarFocus: 'future-perfect',
  },
  {
    id: 'a-fp3',
    sentenceType: 'statement',
    pattern: 'action',
    unhealthy: 'By December, she will have wrote 100 pages.',
    highlightSpan: span('By December, she will have wrote 100 pages.', 'wrote'),
    errorTags: ['verb-form'],
    correctHelper: 'will',
    healthy: 'By December, she will have written 100 pages.',
    subject: 'she',
    baseVerb: 'write',
    explanation: 'After HAVE, use the PAST PARTICIPLE: write → wrote → WRITTEN. "Will have written" (not "will have wrote").',
    hint: 'will have + past participle (written, gone, done, seen, eaten).',
    tier: 'advanced', complexity: 4, grammarFocus: 'future-perfect',
  },
  {
    id: 'a-fp4',
    sentenceType: 'question',
    pattern: 'action',
    unhealthy: 'Will you finished the report by Friday?',
    highlightSpan: span('Will you finished the report by Friday?', 'finished'),
    errorTags: ['missing-word'],
    correctHelper: 'will',
    healthy: 'Will you have finished the report by Friday?',
    subject: 'you',
    baseVerb: 'finish',
    explanation: 'Future perfect question: WILL + subject + HAVE + past participle. You need HAVE between "you" and "finished".',
    hint: 'Future perfect Q: WILL + subject + HAVE + past participle.',
    tier: 'advanced', complexity: 4, grammarFocus: 'future-perfect',
  },
  {
    id: 'a-fp5',
    sentenceType: 'statement',
    pattern: 'action',
    unhealthy: 'By 2030, scientists have found a cure for many diseases.',
    highlightSpan: span('By 2030, scientists have found a cure for many diseases.', 'have'),
    errorTags: ['missing-word'],
    correctHelper: 'will',
    healthy: 'By 2030, scientists will have found a cure for many diseases.',
    subject: 'scientists',
    baseVerb: 'find',
    explanation: '"By 2030" is a future time → need WILL HAVE. "Have found" alone is present perfect (up to now), not far enough.',
    hint: '2030 is the future → WILL have found.',
    tier: 'advanced', complexity: 4, grammarFocus: 'future-perfect',
  },
  {
    id: 'a-fp6',
    sentenceType: 'negative',
    pattern: 'action',
    unhealthy: "By 9pm, we won't ate dinner yet.",
    highlightSpan: span("By 9pm, we won't ate dinner yet.", "won't ate"),
    errorTags: ['missing-word', 'verb-form'],
    correctHelper: 'will',
    healthy: "By 9pm, we won't have eaten dinner yet.",
    subject: 'we',
    baseVerb: 'eat',
    explanation: 'Future perfect negative: WON\'T HAVE + past participle. Missing HAVE, and "ate" should be the participle EATEN.',
    hint: "won't have + past participle (eaten, gone, finished).",
    tier: 'advanced', complexity: 5, grammarFocus: 'future-perfect',
  },

  // ─── PRESENT PERFECT CONTINUOUS — have / has been + -ing (8) ──────────
  // For an action that started in the past and is still happening (or has
  // very recent results). The double helper (HAVE + BEEN) is what trips
  // learners up the most.
  {
    id: 'a-ppc1',
    sentenceType: 'statement',
    pattern: 'action',
    unhealthy: 'I have been work here for three years.',
    highlightSpan: span('I have been work here for three years.', 'work'),
    errorTags: ['verb-form'],
    correctHelper: 'have',
    healthy: 'I have been working here for three years.',
    subject: 'I',
    baseVerb: 'work',
    explanation: 'Present perfect continuous = HAVE/HAS + BEEN + -ing. After BEEN, the main verb gets -ing: "working", not "work".',
    hint: 'have/has + been + verb-ing.',
    tier: 'advanced', complexity: 3, grammarFocus: 'present-perfect-continuous',
  },
  {
    id: 'a-ppc2',
    sentenceType: 'statement',
    pattern: 'action',
    unhealthy: 'She has been studying English since five years.',
    highlightSpan: span('She has been studying English since five years.', 'since'),
    errorTags: ['extra-word'],
    correctHelper: 'has',
    healthy: 'She has been studying English for five years.',
    subject: 'she',
    baseVerb: 'study',
    explanation: 'The verb form is right, but: SINCE + starting point ("since 2020", "since Monday"), FOR + length of time ("for five years").',
    hint: 'for + duration · since + starting point.',
    tier: 'advanced', complexity: 3, grammarFocus: 'present-perfect-continuous',
  },
  {
    id: 'a-ppc3',
    sentenceType: 'statement',
    pattern: 'action',
    unhealthy: 'They has been waiting for an hour.',
    highlightSpan: span('They has been waiting for an hour.', 'has'),
    errorTags: ['verb-form'],
    correctHelper: 'have',
    healthy: 'They have been waiting for an hour.',
    subject: 'they',
    baseVerb: 'wait',
    explanation: '"They" takes HAVE, not HAS. Same rule as the simple present-perfect: I/you/we/they → have, he/she/it → has.',
    hint: 'they/we/you/I → have been · he/she/it → has been.',
    tier: 'advanced', complexity: 2, grammarFocus: 'present-perfect-continuous',
  },
  {
    id: 'a-ppc4',
    sentenceType: 'statement',
    pattern: 'action',
    unhealthy: 'My eyes are red because I am been crying.',
    highlightSpan: span('My eyes are red because I am been crying.', 'am been'),
    errorTags: ['wrong-helper'],
    correctHelper: 'have',
    healthy: 'My eyes are red because I have been crying.',
    subject: 'I',
    baseVerb: 'cry',
    explanation: 'Recent ongoing action with present results → HAVE BEEN + -ing. "Am been" mixes present BE with a past participle, which doesn\'t work.',
    hint: 'Recent results / still happening → have been + -ing.',
    tier: 'advanced', complexity: 4, grammarFocus: 'present-perfect-continuous',
  },
  {
    id: 'a-ppc5',
    sentenceType: 'question',
    pattern: 'action',
    unhealthy: 'How long you have been living here?',
    highlightSpan: span('How long you have been living here?', 'you have'),
    errorTags: ['word-order'],
    correctHelper: 'have',
    healthy: 'How long have you been living here?',
    subject: 'you',
    baseVerb: 'live',
    explanation: 'Question word order: WH + HAVE/HAS + subject + BEEN + -ing. "Have you", not "you have".',
    hint: 'WH + HAVE + subject + been + verb-ing.',
    tier: 'advanced', complexity: 4, grammarFocus: 'present-perfect-continuous',
  },
  {
    id: 'a-ppc6',
    sentenceType: 'statement',
    pattern: 'action',
    unhealthy: 'He has been worked on that project all morning.',
    highlightSpan: span('He has been worked on that project all morning.', 'worked'),
    errorTags: ['verb-form'],
    correctHelper: 'has',
    healthy: 'He has been working on that project all morning.',
    subject: 'he',
    baseVerb: 'work',
    explanation: 'After BEEN, use -ing for ongoing actions: "been working". "Been worked" sounds passive ("he has been worked on" = someone is doing it to him).',
    hint: 'been + verb-ing (active, ongoing).',
    tier: 'advanced', complexity: 4, grammarFocus: 'present-perfect-continuous',
  },
  {
    id: 'a-ppc7',
    sentenceType: 'negative',
    pattern: 'action',
    unhealthy: "We don't have been sleeping well lately.",
    highlightSpan: span("We don't have been sleeping well lately.", "don't have"),
    errorTags: ['extra-word', 'wrong-helper'],
    correctHelper: 'have',
    healthy: "We haven't been sleeping well lately.",
    acceptable: ['We have not been sleeping well lately.'],
    subject: 'we',
    baseVerb: 'sleep',
    explanation: 'HAVE negates itself: HAVE NOT → HAVEN\'T. Don\'t add DON\'T — the helper already does that job.',
    hint: "Perfect negative: haven't / hasn't (no don't / doesn't).",
    tier: 'advanced', complexity: 4, grammarFocus: 'present-perfect-continuous',
  },
  {
    id: 'a-ppc8',
    sentenceType: 'statement',
    pattern: 'action',
    unhealthy: "It's been raining since two hours.",
    highlightSpan: span("It's been raining since two hours.", 'since'),
    errorTags: ['extra-word'],
    correctHelper: 'has',
    healthy: "It's been raining for two hours.",
    acceptable: ['It has been raining for two hours.'],
    subject: 'it',
    baseVerb: 'rain',
    explanation: 'Two hours is a LENGTH of time → FOR. SINCE only takes a starting point ("since 3pm", "since this morning").',
    hint: 'two hours / five years / a week → FOR.',
    tier: 'advanced', complexity: 3, grammarFocus: 'present-perfect-continuous',
  },

  // ─── PAST PERFECT CONTINUOUS — had been + -ing (6) ─────────────────────
  // For an action that was ongoing UP TO a past moment. The trap: confusing
  // with past continuous (was/were + -ing) or with present perfect continuous.
  {
    id: 'a-papc1',
    sentenceType: 'statement',
    pattern: 'action',
    unhealthy: 'She was been working for hours when the boss arrived.',
    highlightSpan: span('She was been working for hours when the boss arrived.', 'was been'),
    errorTags: ['wrong-helper'],
    correctHelper: 'had',
    healthy: 'She had been working for hours when the boss arrived.',
    subject: 'she',
    baseVerb: 'work',
    explanation: 'Past perfect continuous = HAD BEEN + -ing. "Was been" doesn\'t exist in English — past BE can\'t take BEEN.',
    hint: 'Ongoing action before a past moment → HAD BEEN + -ing.',
    tier: 'advanced', complexity: 4, grammarFocus: 'past-perfect-continuous',
  },
  {
    id: 'a-papc2',
    sentenceType: 'statement',
    pattern: 'action',
    unhealthy: 'They had been wait for two hours when we finally arrived.',
    highlightSpan: span('They had been wait for two hours when we finally arrived.', 'wait'),
    errorTags: ['verb-form'],
    correctHelper: 'had',
    healthy: 'They had been waiting for two hours when we finally arrived.',
    subject: 'they',
    baseVerb: 'wait',
    explanation: 'After BEEN, the verb takes -ing: "waiting", not "wait". HAD + BEEN + verb-ing.',
    hint: 'had been + verb-ing.',
    tier: 'advanced', complexity: 3, grammarFocus: 'past-perfect-continuous',
  },
  {
    id: 'a-papc3',
    sentenceType: 'statement',
    pattern: 'action',
    unhealthy: 'I have been studying all night before the exam.',
    highlightSpan: span('I have been studying all night before the exam.', 'have'),
    errorTags: ['wrong-helper'],
    correctHelper: 'had',
    healthy: 'I had been studying all night before the exam.',
    subject: 'I',
    baseVerb: 'study',
    explanation: '"Before the exam" sets a past reference. The studying happened before that → HAD BEEN, not HAVE BEEN. HAVE BEEN connects to right now.',
    hint: 'Before / by + past time → HAD been (not have been).',
    tier: 'advanced', complexity: 5, grammarFocus: 'past-perfect-continuous',
  },
  {
    id: 'a-papc4',
    sentenceType: 'statement',
    pattern: 'action',
    unhealthy: 'He had been worked at that company for ten years before it closed.',
    highlightSpan: span('He had been worked at that company for ten years before it closed.', 'worked'),
    errorTags: ['verb-form'],
    correctHelper: 'had',
    healthy: 'He had been working at that company for ten years before it closed.',
    subject: 'he',
    baseVerb: 'work',
    explanation: 'After BEEN, use -ing for active continuous: "working". "Been worked" would be passive (someone doing it TO him).',
    hint: 'been + verb-ing (active continuous).',
    tier: 'advanced', complexity: 4, grammarFocus: 'past-perfect-continuous',
  },
  {
    id: 'a-papc5',
    sentenceType: 'statement',
    pattern: 'action',
    unhealthy: 'The streets were wet because it had been rain all morning.',
    highlightSpan: span('The streets were wet because it had been rain all morning.', 'rain'),
    errorTags: ['verb-form'],
    correctHelper: 'had',
    healthy: 'The streets were wet because it had been raining all morning.',
    subject: 'it',
    baseVerb: 'rain',
    explanation: 'Past results of an earlier ongoing action → HAD BEEN + -ing. "Had been raining" — base form "rain" doesn\'t work after BEEN.',
    hint: 'had been + verb-ing.',
    tier: 'advanced', complexity: 4, grammarFocus: 'past-perfect-continuous',
  },
  {
    id: 'a-papc6',
    sentenceType: 'question',
    pattern: 'action',
    unhealthy: 'How long they had been waiting when you arrived?',
    highlightSpan: span('How long they had been waiting when you arrived?', 'they had'),
    errorTags: ['word-order'],
    correctHelper: 'had',
    healthy: 'How long had they been waiting when you arrived?',
    subject: 'they',
    baseVerb: 'wait',
    explanation: 'Question inversion: WH + HAD + subject + BEEN + -ing. "Had they", not "they had".',
    hint: 'WH + HAD + subject + been + verb-ing.',
    tier: 'advanced', complexity: 4, grammarFocus: 'past-perfect-continuous',
  },

  // ─── MIXED-HELPER TRAPS (continuous + helper combined) (7) ────────────
  {
    id: 'a-mh1',
    sentenceType: 'question',
    pattern: 'action',
    unhealthy: 'How long do you living here?',
    highlightSpan: span('How long do you living here?', 'do you living'),
    errorTags: ['wrong-helper', 'verb-form'],
    correctHelper: 'have',
    healthy: 'How long have you been living here?',
    acceptable: ['How long have you lived here?'],
    subject: 'you',
    baseVerb: 'live',
    explanation: '"How long" with an ongoing action → present perfect (or perfect continuous). HAVE + been + -ing.',
    hint: '"How long…" + ongoing situation → have + been + -ing.',
    tier: 'advanced', complexity: 5, grammarFocus: 'mixed-helper',
  },
  {
    id: 'a-mh2',
    sentenceType: 'question',
    pattern: 'action',
    unhealthy: 'What does she doing right now?',
    highlightSpan: span('What does she doing right now?', 'does she doing'),
    errorTags: ['wrong-helper'],
    correctHelper: 'is',
    healthy: 'What is she doing right now?',
    subject: 'she',
    baseVerb: 'do',
    explanation: '"Right now" = present continuous → BE + -ing. Drop DOES; use IS + DOING.',
    hint: '"Right now / at the moment" → BE + -ing.',
    tier: 'advanced', complexity: 4, grammarFocus: 'mixed-helper',
  },
  {
    id: 'a-mh3',
    sentenceType: 'statement',
    pattern: 'action',
    unhealthy: 'I am work in a restaurant for five years.',
    highlightSpan: span('I am work in a restaurant for five years.', 'am work'),
    errorTags: ['wrong-helper'],
    correctHelper: 'have',
    healthy: 'I have worked in a restaurant for five years.',
    acceptable: ['I have been working in a restaurant for five years.'],
    subject: 'I',
    baseVerb: 'work',
    explanation: '"For five years" with a still-true situation → present perfect: HAVE + past participle (or HAVE BEEN + -ing for emphasis on the duration).',
    hint: 'for / since + duration → have / has + past participle.',
    tier: 'advanced', complexity: 5, grammarFocus: 'mixed-helper',
  },
  {
    id: 'a-mh4',
    sentenceType: 'question',
    pattern: 'action',
    unhealthy: 'Are you been to the new café yet?',
    highlightSpan: span('Are you been to the new café yet?', 'Are'),
    errorTags: ['wrong-helper'],
    correctHelper: 'have',
    healthy: 'Have you been to the new café yet?',
    subject: 'you',
    baseVerb: 'be',
    explanation: '"Yet" = present perfect signal. Question form: HAVE + subject + been. "Are you been" mixes BE with a past participle illegally.',
    hint: 'yet / already / ever → present perfect (HAVE + been / done / seen).',
    tier: 'advanced', complexity: 4, grammarFocus: 'mixed-helper',
  },
  {
    id: 'a-mh5',
    sentenceType: 'statement',
    pattern: 'action',
    unhealthy: 'She was study when the phone rang.',
    highlightSpan: span('She was study when the phone rang.', 'was study'),
    errorTags: ['verb-form'],
    correctHelper: 'was',
    healthy: 'She was studying when the phone rang.',
    subject: 'she',
    baseVerb: 'study',
    explanation: 'Past continuous = WAS / WERE + -ing. "Was studying", not "was study".',
    hint: 'Past continuous: was/were + verb-ing.',
    tier: 'advanced', complexity: 3, grammarFocus: 'mixed-helper',
  },
  {
    id: 'a-mh6',
    sentenceType: 'question',
    pattern: 'action',
    unhealthy: 'Did you ever lived in another country?',
    highlightSpan: span('Did you ever lived in another country?', 'Did'),
    errorTags: ['wrong-helper'],
    correctHelper: 'have',
    healthy: 'Have you ever lived in another country?',
    subject: 'you',
    baseVerb: 'live',
    explanation: '"Ever" = at any time up to now → present perfect with HAVE, not the past simple with DID. "Have you ever lived…?"',
    hint: 'ever + life experience → HAVE + past participle.',
    tier: 'advanced', complexity: 4, grammarFocus: 'mixed-helper',
  },
  {
    id: 'a-mh7',
    sentenceType: 'statement',
    pattern: 'action',
    unhealthy: 'If I will see her, I will tell her.',
    highlightSpan: span('If I will see her, I will tell her.', 'will see'),
    errorTags: ['wrong-helper'],
    correctHelper: 'will',
    healthy: 'If I see her, I will tell her.',
    subject: 'I',
    baseVerb: 'see',
    explanation: 'First conditional: IF + present simple, WILL + base verb. No "will" in the IF clause.',
    hint: '1st conditional: IF + present, WILL + base. (Never "if + will".)',
    tier: 'advanced', complexity: 5, grammarFocus: 'mixed-helper',
  },
];

const cases: GrammarHospitalCase[] = [
  ...beginnerCases,
  ...intermediateCases,
  ...advancedCases,
];

const content: GrammarHospitalContent = {
  type: 'grammar-hospital',
  title: ACTIVITY_TITLE,
  description:
    "Diagnose what's wrong with each sentence, choose the right helper, and repair it. Levels: Beginner (do / does / be), Intermediate (past simple, present perfect, agreement), Advanced (modals, embedded questions, tag questions). Open the gear icon to change difficulty.",
  level: 'beginner',
  cases,
  participationPoints: 5,
  released: true,
};

async function main() {
  const counts = {
    beginner: beginnerCases.length,
    intermediate: intermediateCases.length,
    advanced: advancedCases.length,
  };
  console.log(
    `Seeding ${ACTIVITY_TITLE}…  total ${cases.length} cases ` +
      `(beginner ${counts.beginner} · intermediate ${counts.intermediate} · advanced ${counts.advanced})`
  );

  const data = {
    title: ACTIVITY_TITLE,
    description: content.description ?? null,
    content: JSON.stringify(content),
    type: 'game',
    ui: 'grammar-hospital',
    category: 'games',
    level: 'beginner',
    isReleased: true,
  };

  const existing = await prisma.activity.findFirst({ where: { title: ACTIVITY_TITLE } });

  if (existing) {
    await prisma.activity.update({ where: { id: existing.id }, data });
    console.log(`Updated existing activity: ${existing.id}`);
  } else {
    const created = await prisma.activity.create({ data });
    console.log(`Created new activity: ${created.id}`);
  }

  console.log('\nDone! Grammar Hospital deck refreshed with all three tiers.');
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
