/** New contextual questions: one use of each focus verb, separate from recall. */
export const WEEKLY_VERB_APPLICATIONS: [string, string, string, string][] = [
  ['She ___ ready to study. (be)', 'is', 'He ___ a reference sheet. (have)', 'has'],
  ['I have already ___ my homework. (do)', 'done', 'She has just ___ a study plan. (make)', 'made'],
  ['Yesterday, I ___ to the library. (go)', 'went', 'Please ___ to the front desk. (come)', 'come'],
  ['Can you ___ me your phone number? (tell)', 'tell', 'You should ___ your name clearly. (say)', 'say'],
  ['Have you ever ___ food to a neighbor? (take)', 'taken', 'We have ___ extra bags for the volunteers. (bring)', 'brought'],
  ['I enjoy ___ new neighbors. (meet)', 'meeting', 'She is good at ___ in public. (speak)', 'speaking'],
  ['Let’s ___ a letter to the council. (write)', 'write', 'Why don’t we ___ an email? (send)', 'send'],
  ['If we ___ carefully, we will find a solution. (think)', 'think', 'If she ___ the answer, she will tell us. (know)', 'knows'],
  ['The smaller package ___ less than the large one. (cost)', 'costs', 'Last week, we ___ less on groceries. (spend)', 'spent'],
  ['Yesterday, I ___ the cheaper phone. (buy)', 'bought', 'This shop ___ the most affordable furniture. (sell)', 'sells'],
  ['She ___ rice with dinner every day. (eat)', 'eats', 'Yesterday, I ___ some water after lunch. (drink)', 'drank'],
  ['Did you ___ the apartment yesterday? (see)', 'see', 'Where did you ___ the rental listing? (find)', 'find'],
  ['We have to ___ an apartment this week. (choose)', 'choose', 'The landlord doesn’t ___ tenants smoke inside. (let)', 'let'],
  ['I need to report that the window ___ yesterday. (break)', 'broke', 'Could you ___ the door open, please? (hold)', 'hold'],
  ['I was cooking when I ___ a loud noise. (hear)', 'heard', 'While I was locking the door, my neighbor ___ the building. (leave)', 'left'],
  ['Before I applied, I had ___ a team leader. (become)', 'become', 'She had ___ two projects before her promotion. (lead)', 'led'],
  ['You must ___ safety shoes here. (wear)', 'wear', 'Employees have to ___ the exit clear. (keep)', 'keep'],
  ['If I ___ a free trip, I would visit my family. (win)', 'won', 'If she ___ to Boston, I would meet her at the airport. (fly)', 'flew'],
  ['Please ___ the boxes away after your shift. (put)', 'put', 'Yesterday, I ___ along well with the new team. (get)', 'got'],
  ['I have ___ the safety rules since orientation. (understand)', 'understood', 'What does this job title ___? (mean)', 'mean'],
  ['Our team has been ___ steadily this year. (grow)', 'growing', 'I have been ___ my computer skills. (build)', 'building'],
  ['She enjoys ___ new employees. (teach)', 'teaching', 'I want to ___ you my work. (show)', 'show'],
  ['Workers are ___ every Friday. (pay)', 'paid', 'The instructions were ___ to every employee. (give)', 'given'],
  ['If you ___ dizzy, you should sit down. (feel)', 'feel', 'You should ___ more when you are tired. (sleep)', 'sleep'],
  ['I stopped walking because I ___ yesterday. (fall)', 'fell', 'My knee ___ when I bend it. (hurt)', 'hurts'],
  ['The nurse said she ___ beside me during the test. (sit: simple past)', 'sat', 'The doctor said I should ___ up slowly. (stand)', 'stand'],
  ['If I had not ___ my medicine, I would have felt better. (forget)', 'forgotten', 'If she had ___ the label, she would have noticed the warning. (read)', 'read'],
  ['I used to ___ every morning. (run)', 'run', 'Now she ___ her bike to work. (ride)', 'rides'],
  ['I am used to ___ in city traffic. (drive)', 'driving', 'She is getting used to ___ up early. (wake)', 'waking'],
  ['If I ___ my keys yesterday, I would have called you. (lose: use the past perfect)', 'had lost', 'If I ___ my finger, I will clean it. (cut)', 'cut'],
  ['We plan to ___ our new routine tomorrow. (begin)', 'begin', 'He is thinking about ___ smoking. (quit)', 'quitting'],
  ['Someone ___ my bike last year. (steal)', 'stole', 'The water has ___ overnight. (freeze)', 'frozen'],
  ['She has ___ the early bus all week. (catch)', 'caught', 'They ___ for better working conditions last year. (fight)', 'fought'],
  ['The ball ___ the window yesterday. (hit)', 'hit', 'Could you ___ me a pen? (lend)', 'lend'],
];
