// Auto-generated by scripts/content/fetch-medical-instructions-images.ts
// Run: npm run content:medical-images
// All images are from Unsplash — credit field should be rendered with each image.

export interface MedicalSceneImage {
  url: string;
  alt: string;
  unsplashId: string;
  unsplashPage: string;
  credit: { name: string; url: string };
}

export const medicalInstructionsImages: Record<string, MedicalSceneImage> = {
  triageWaiting: {
    url: "https://images.unsplash.com/photo-1755995083683-50d08cd83d09?w=1200&q=80&auto=format&fit=crop",
    alt: "A bright, well-lit hospital hallway with doors and clear overhead lighting.",
    unsplashId: "jhSkpyCwJI0",
    unsplashPage: "https://unsplash.com/photos/well-lit-hospital-hallway-with-doors-at-the-end-of-the-corridor-jhSkpyCwJI0",
    credit: {
      name: "Fabio Sasso",
      url: "https://unsplash.com/@abduzeedo",
    },
  },
  pharmacyCounter: {
    url: "https://images.unsplash.com/photo-1648824571682-109acc138294?w=1200&q=80&auto=format&fit=crop",
    alt: "A pharmacist handing a prescription bag across a pharmacy counter.",
    unsplashId: "zUe3lwqrRIU",
    unsplashPage: "https://unsplash.com/photos/a-woman-standing-at-a-counter-in-a-store-zUe3lwqrRIU",
    credit: {
      name: "Cova Software",
      url: "https://unsplash.com/@covasoftware",
    },
  },
  pillBottleLabel: {
    url: "https://images.unsplash.com/photo-1675521005096-729123cd1dc8?w=1200&q=80&auto=format&fit=crop",
    alt: "An orange prescription pill bottle with a printed medication label.",
    unsplashId: "Xql9FpeQPCc",
    unsplashPage: "https://unsplash.com/photos/a-close-up-of-a-pill-bottle-with-pills-spilling-out-of-it-Xql9FpeQPCc",
    credit: {
      name: "Lance Reis",
      url: "https://unsplash.com/@lancereis",
    },
  },
  stethoscopeDesk: {
    url: "https://images.unsplash.com/photo-1526256262350-7da7584cf5eb?w=1200&q=80&auto=format&fit=crop",
    alt: "A stethoscope resting on a clipboard on a doctor's desk.",
    unsplashId: "k7ll1hpdhFA",
    unsplashPage: "https://unsplash.com/photos/black-stethoscope-with-brown-leather-case-k7ll1hpdhFA",
    credit: {
      name: "Marcelo Leal",
      url: "https://unsplash.com/@marceloleal80",
    },
  },
  doctorPatientConsult: {
    url: "https://images.unsplash.com/photo-1758691462878-6edc3d3da1be?w=1200&q=80&auto=format&fit=crop",
    alt: "A doctor in a white coat explaining something to a seated patient.",
    unsplashId: "iyeUwItlIPk",
    unsplashPage: "https://unsplash.com/photos/doctor-consults-with-patient-in-medical-office-iyeUwItlIPk",
    credit: {
      name: "Vitaly Gariev",
      url: "https://unsplash.com/@silverkblack",
    },
  },
  clinicSign: {
    url: "https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=1200&q=80&auto=format&fit=crop",
    alt: "A wayfinding sign outside a clinic entrance.",
    unsplashId: "nMyM7fxpokE",
    unsplashPage: "https://unsplash.com/photos/white-concrete-counter-stand-nMyM7fxpokE",
    credit: {
      name: "Martha Dominguez de Gouveia",
      url: "https://unsplash.com/@m_dominguez_marketing",
    },
  },
  nurseInstructions: {
    url: "https://images.unsplash.com/photo-1673865641073-4479f93a7776?w=1200&q=80&auto=format&fit=crop",
    alt: "A healthcare professional in a white coat explaining instructions.",
    unsplashId: "ODM_VsTM2QQ",
    unsplashPage: "https://unsplash.com/photos/a-woman-in-a-white-lab-coat-pointing-at-something-ODM_VsTM2QQ",
    credit: {
      name: "Bermix Studio",
      url: "https://unsplash.com/@bermixstudio",
    },
  },
  clipboardFasting: {
    url: "https://images.unsplash.com/photo-1693683223469-e3da9e2a723d?w=1200&q=80&auto=format&fit=crop",
    alt: "A clinician writing notes on a clipboard chart.",
    unsplashId: "WNlFy0_apVQ",
    unsplashPage: "https://unsplash.com/photos/a-close-up-of-a-person-holding-a-cell-phone-WNlFy0_apVQ",
    credit: {
      name: "Vladislav Igumnov",
      url: "https://unsplash.com/@hansis666",
    },
  },
  hospitalHallway: {
    url: "https://images.unsplash.com/photo-1584451049700-ec9b394f3805?w=1200&q=80&auto=format&fit=crop",
    alt: "A bright, modern hospital corridor leading to exam rooms.",
    unsplashId: "Wn77gCRoegs",
    unsplashPage: "https://unsplash.com/photos/white-and-red-exit-sign-Wn77gCRoegs",
    credit: {
      name: "Cory Mogk",
      url: "https://unsplash.com/@corymogk",
    },
  },
  receptionDesk: {
    url: "https://images.unsplash.com/photo-1764727291644-5dcb0b1a0375?w=1200&q=80&auto=format&fit=crop",
    alt: "A patient checking in at a clinic reception desk.",
    unsplashId: "27zLImvxwV0",
    unsplashPage: "https://unsplash.com/photos/modern-reception-desk-with-sign-overhead-27zLImvxwV0",
    credit: {
      name: "Malcolm Choong 鍾声耀",
      url: "https://unsplash.com/@malcolm_choong",
    },
  },
  recoveryHome: {
    url: "https://images.unsplash.com/photo-1640087975859-f2e7a8d09634?w=1200&q=80&auto=format&fit=crop",
    alt: "A person resting at home on a couch with a blanket and a cup of tea.",
    unsplashId: "r_K7rCRTeUI",
    unsplashPage: "https://unsplash.com/photos/a-woman-sitting-on-a-couch-holding-a-glass-of-water-r_K7rCRTeUI",
    credit: {
      name: "Julian Bock",
      url: "https://unsplash.com/@grafik_bock",
    },
  },
  workplaceEmailLaptop: {
    url: "https://images.unsplash.com/photo-1758522484158-abdb72a85a51?w=1200&q=80&auto=format&fit=crop",
    alt: "A person at a laptop writing a message, coffee beside them.",
    unsplashId: "8qKi1nt5P2Y",
    unsplashPage: "https://unsplash.com/photos/man-on-phone-and-laptop-at-kitchen-table-8qKi1nt5P2Y",
    credit: {
      name: "Vitaly Gariev",
      url: "https://unsplash.com/@silverkblack",
    },
  },
} as const;
