// Auto-generated by scripts/content/fetch-medicine-labels-images.ts
// Run: npm run content:medicine-images
// Images are from free Pexels/Unsplash sources — credit field should be rendered with each image.

export interface MedicineLabelSceneImage {
  url: string;
  alt: string;
  unsplashId: string;
  unsplashPage: string;
  credit: { name: string; url: string };
  sourceLabel?: string;
  maxHeight?: string;
  objectFit?: "cover" | "contain";
}

export const medicineLabelsImages: Record<string, MedicineLabelSceneImage> = {
  pillBottleClose: {
    url: "https://images.unsplash.com/photo-1739289696449-cba3a5ef085d?w=1200&q=80&auto=format&fit=crop",
    alt: "A man and a woman looking at items in a store aisle.",
    unsplashId: "uNawp6qgpcE",
    unsplashPage: "https://unsplash.com/photos/a-man-and-a-woman-looking-at-items-in-a-store-uNawp6qgpcE",
    credit: {
      name: "Ninthgrid",
      url: "https://unsplash.com/@ninthgrid",
    },
  },
  imperativeMeds: {
    url: "/images/medicine-labels/imperative-meds.png",
    alt: "Unbranded medicine bottles with clear label directions using imperative verbs.",
    unsplashId: "local-ai-imperative-meds",
    unsplashPage: "",
    credit: {
      name: "AI-generated classroom image",
      url: "",
    },
    sourceLabel: "Local image",
  },
  dosingLanguage: {
    url: "/images/medicine-labels/dosing.png",
    alt: "Unbranded liquid medicine with a dosing syringe, measuring cup, and simple dose schedule.",
    unsplashId: "local-ai-dosing-language",
    unsplashPage: "",
    credit: {
      name: "AI-generated classroom image",
      url: "",
    },
    sourceLabel: "Local image",
    maxHeight: "none",
    objectFit: "contain",
  },
  medicineCabinet: {
    url: "https://images.unsplash.com/photo-1595432576728-94e0e94a7663?w=1200&q=80&auto=format&fit=crop",
    alt: "Rows of medicine bottles organized on pharmacy shelves.",
    unsplashId: "Y5N3uPzJayk",
    unsplashPage: "https://unsplash.com/photos/white-and-black-plastic-bottles-Y5N3uPzJayk",
    credit: {
      name: "Chelms Varthoumlien",
      url: "https://unsplash.com/@varlien",
    },
  },
  pharmacyCounter: {
    url: "https://images.unsplash.com/photo-1580281657527-47f249e8f4df?w=1200&q=80&auto=format&fit=crop",
    alt: "A pharmacist handing a prescription bag across a pharmacy counter.",
    unsplashId: "byGTytEGjBo",
    unsplashPage: "https://unsplash.com/photos/man-in-white-dress-shirt-holding-white-box-byGTytEGjBo",
    credit: {
      name: "National Cancer Institute",
      url: "https://unsplash.com/@nci",
    },
  },
  medicineSpoon: {
    url: "https://images.unsplash.com/photo-1590483086519-dd5e99b51c3c?w=1200&q=80&auto=format&fit=crop",
    alt: "A measuring spoon with liquid medicine, used for children's dosing.",
    unsplashId: "lgOtXgWmvRw",
    unsplashPage: "https://unsplash.com/photos/yellow-plastic-measuring-cup-on-white-surface-lgOtXgWmvRw",
    credit: {
      name: "Glen Carrie",
      url: "https://unsplash.com/@glencarrie",
    },
  },
  parentChild: {
    url: "https://images.unsplash.com/photo-1625055929490-1ced51017e72?w=1200&q=80&auto=format&fit=crop",
    alt: "An orange and white medicine bottle with pills spilled into a person's hand.",
    unsplashId: "hn2hQoALBCk",
    unsplashPage: "https://unsplash.com/photos/orange-and-white-plastic-bottle-on-white-textile-hn2hQoALBCk",
    credit: {
      name: "Towfiqu barbhuiya",
      url: "https://unsplash.com/@towfiqu999999",
    },
  },
  pharmacyAisle: {
    url: "https://images.unsplash.com/photo-1576602976047-174e57a47881?w=1200&q=80&auto=format&fit=crop",
    alt: "A pharmacy store aisle with over-the-counter medicine products on shelves.",
    unsplashId: "747NDboAWNY",
    unsplashPage: "https://unsplash.com/photos/empty-white-painted-store-747NDboAWNY",
    credit: {
      name: "Nathaniel Yeo",
      url: "https://unsplash.com/@nathanielyeo",
    },
  },
  insuranceCard: {
    url: "https://images.unsplash.com/photo-1619590530358-d4f0c3f8bbec?w=1200&q=80&auto=format&fit=crop",
    alt: "Hands holding a health insurance card.",
    unsplashId: "7dtOV1RYg5Y",
    unsplashPage: "https://unsplash.com/photos/black-and-gray-electronic-device-7dtOV1RYg5Y",
    credit: {
      name: "Stebilex Systems",
      url: "https://unsplash.com/@stebilexsystems",
    },
  },
  doctorReception: {
    url: "https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=1200&q=80&auto=format&fit=crop",
    alt: "A patient checking in at a doctor's office reception desk.",
    unsplashId: "nMyM7fxpokE",
    unsplashPage: "https://unsplash.com/photos/white-concrete-counter-stand-nMyM7fxpokE",
    credit: {
      name: "Martha Dominguez de Gouveia",
      url: "https://unsplash.com/@m_dominguez_marketing",
    },
  },
  enrollmentPaperwork: {
    url: "https://images.unsplash.com/photo-1631540702177-d2b28aa09fb0?w=1200&q=80&auto=format&fit=crop",
    alt: "A person filling out healthcare enrollment paperwork with a pen.",
    unsplashId: "AVERPZyQAaI",
    unsplashPage: "https://unsplash.com/photos/a-person-is-filling-out-a-form-with-a-pen-AVERPZyQAaI",
    credit: {
      name: "Mika Baumeister",
      url: "https://unsplash.com/@kommumikation",
    },
  },
} as const;
