// Auto-generated by scripts/content/fetch-reported-speech-images.ts
// Run: npm run content:reported-speech-images
// All images are from Unsplash — credit field should be rendered with each image.
// Seeded defaults align with curated medical guide photos until refetched.

export interface ReportedSpeechSceneImage {
  url: string;
  alt: string;
  unsplashId: string;
  unsplashPage: string;
  credit: { name: string; url: string };
}

export const reportedSpeechImages: Record<string, ReportedSpeechSceneImage> = {
  sceneMychartPing: {
    url: "https://images.unsplash.com/photo-1640087975859-f2e7a8d09634?w=1200&q=80&auto=format&fit=crop",
    alt: "A person at home on a couch checking messages on a smartphone.",
    unsplashId: "r_K7rCRTeUI",
    unsplashPage: "https://unsplash.com/photos/a-woman-sitting-on-a-couch-holding-a-glass-of-water-r_K7rCRTeUI",
    credit: {
      name: "Julian Bock",
      url: "https://unsplash.com/@grafik_bock",
    },
  },
  sceneReception: {
    url: "https://images.unsplash.com/photo-1764727291644-5dcb0b1a0375?w=1200&q=80&auto=format&fit=crop",
    alt: "A patient at a clinic reception desk with paperwork.",
    unsplashId: "27zLImvxwV0",
    unsplashPage: "https://unsplash.com/photos/modern-reception-desk-with-sign-overhead-27zLImvxwV0",
    credit: {
      name: "Malcolm Choong 鍾声耀",
      url: "https://unsplash.com/@malcolm_choong",
    },
  },
  sceneExamRoom: {
    url: "https://images.unsplash.com/photo-1758691462878-6edc3d3da1be?w=1200&q=80&auto=format&fit=crop",
    alt: "A doctor talking with a patient in an exam room.",
    unsplashId: "iyeUwItlIPk",
    unsplashPage: "https://unsplash.com/photos/doctor-consults-with-patient-in-medical-office-iyeUwItlIPk",
    credit: {
      name: "Vitaly Gariev",
      url: "https://unsplash.com/@silverkblack",
    },
  },
  sceneNurseInstructions: {
    url: "https://images.unsplash.com/photo-1673865641073-4479f93a7776?w=1200&q=80&auto=format&fit=crop",
    alt: "A nurse explaining next steps to a patient.",
    unsplashId: "ODM_VsTM2QQ",
    unsplashPage: "https://unsplash.com/photos/a-woman-in-a-white-lab-coat-pointing-at-something-ODM_VsTM2QQ",
    credit: {
      name: "Bermix Studio",
      url: "https://unsplash.com/@bermixstudio",
    },
  },
  sceneHospitalHall: {
    url: "https://images.unsplash.com/photo-1584451049700-ec9b394f3805?w=1200&q=80&auto=format&fit=crop",
    alt: "A bright hospital corridor with exam room doors.",
    unsplashId: "Wn77gCRoegs",
    unsplashPage: "https://unsplash.com/photos/white-and-red-exit-sign-Wn77gCRoegs",
    credit: {
      name: "Cory Mogk",
      url: "https://unsplash.com/@corymogk",
    },
  },
  sceneLabDraw: {
    url: "https://images.unsplash.com/photo-1693683223469-e3da9e2a723d?w=1200&q=80&auto=format&fit=crop",
    alt: "A healthcare setting where lab work is discussed with a patient.",
    unsplashId: "WNlFy0_apVQ",
    unsplashPage: "https://unsplash.com/photos/a-close-up-of-a-person-holding-a-cell-phone-WNlFy0_apVQ",
    credit: {
      name: "Vladislav Igumnov",
      url: "https://unsplash.com/@hansis666",
    },
  },
  scenePharmacy: {
    url: "https://images.unsplash.com/photo-1648824571682-109acc138294?w=1200&q=80&auto=format&fit=crop",
    alt: "A pharmacist at the counter helping a patient with medication.",
    unsplashId: "zUe3lwqrRIU",
    unsplashPage: "https://unsplash.com/photos/a-woman-standing-at-a-counter-in-a-store-zUe3lwqrRIU",
    credit: {
      name: "Cova Software",
      url: "https://unsplash.com/@covasoftware",
    },
  },
  sceneDischargePapers: {
    url: "https://images.unsplash.com/photo-1526256262350-7da7584cf5eb?w=1200&q=80&auto=format&fit=crop",
    alt: "A clinician reviewing discharge paperwork with a patient.",
    unsplashId: "k7ll1hpdhFA",
    unsplashPage: "https://unsplash.com/photos/black-stethoscope-with-brown-leather-case-k7ll1hpdhFA",
    credit: {
      name: "Marcelo Leal",
      url: "https://unsplash.com/@marceloleal80",
    },
  },
  sceneFamilyPhone: {
    url: "https://images.unsplash.com/photo-1758522484158-abdb72a85a51?w=1200&q=80&auto=format&fit=crop",
    alt: "An adult on the phone at home, sharing news with family.",
    unsplashId: "8qKi1nt5P2Y",
    unsplashPage: "https://unsplash.com/photos/man-on-phone-and-laptop-at-kitchen-table-8qKi1nt5P2Y",
    credit: {
      name: "Vitaly Gariev",
      url: "https://unsplash.com/@silverkblack",
    },
  },
} as const;
