// Auto-generated by scripts/content/fetch-reported-speech-images.ts
// Run: npm run content:reported-speech-images
// All images are from Unsplash — credit field should be rendered with each image.
// Unsplash ids used in medical-instructions-images.generated.ts are excluded when refetching.

export interface ReportedSpeechSceneImage {
  url: string;
  alt: string;
  unsplashId: string;
  unsplashPage: string;
  credit: { name: string; url: string };
}

export const reportedSpeechImages: Record<string, ReportedSpeechSceneImage> = {
  sceneMychartPing: {
    url: "https://images.unsplash.com/photo-1598870783716-1c5f0f890aa4?w=1200&q=80&auto=format&fit=crop",
    alt: "A person holding a smartphone, checking messages or a patient portal.",
    unsplashId: "Ayx2M0iiVFQ",
    unsplashPage: "https://unsplash.com/photos/person-holding-black-android-smartphone-Ayx2M0iiVFQ",
    credit: {
      name: "Magnet.me",
      url: "https://unsplash.com/@magnetme",
    },
  },
  sceneReception: {
    url: "https://images.unsplash.com/photo-1633466154727-a4ad283ab8d7?w=1200&q=80&auto=format&fit=crop",
    alt: "A patient in a wheelchair at a clinic reception desk.",
    unsplashId: "n0sFXM_r-mI",
    unsplashPage: "https://unsplash.com/photos/a-woman-sitting-in-a-wheel-chair-in-front-of-a-mirror-n0sFXM_r-mI",
    credit: {
      name: "CDC",
      url: "https://unsplash.com/@cdc",
    },
  },
  sceneExamRoom: {
    url: "https://images.unsplash.com/photo-1631217868264-e5b90bb7e133?w=1200&q=80&auto=format&fit=crop",
    alt: "A clinician in scrubs with a laptop during a medical visit.",
    unsplashId: "tl447mekwuQ",
    unsplashPage: "https://unsplash.com/photos/woman-in-white-scrub-suit-holding-gray-laptop-computer-tl447mekwuQ",
    credit: {
      name: "National Cancer Institute",
      url: "https://unsplash.com/@nci",
    },
  },
  sceneNurseInstructions: {
    url: "https://images.unsplash.com/photo-1631217871099-88310a909a32?w=1200&q=80&auto=format&fit=crop",
    alt: "A healthcare professional explaining something while holding a card or paper.",
    unsplashId: "nR2C9AVzfHY",
    unsplashPage: "https://unsplash.com/photos/woman-in-white-button-up-long-sleeve-shirt-holding-white-card-nR2C9AVzfHY",
    credit: {
      name: "National Cancer Institute",
      url: "https://unsplash.com/@nci",
    },
  },
  sceneHospitalHall: {
    url: "https://images.unsplash.com/photo-1629410484397-a4dcd74088a0?w=1200&q=80&auto=format&fit=crop",
    alt: "A bright, modern white hospital corridor with overhead lighting.",
    unsplashId: "LwXMl6IL-0k",
    unsplashPage: "https://unsplash.com/photos/white-hallway-with-white-light-LwXMl6IL-0k",
    credit: {
      name: "Gonzalo Kenny",
      url: "https://unsplash.com/@gonzakenny",
    },
  },
  sceneLabDraw: {
    url: "https://images.unsplash.com/photo-1631217872822-1c2546d6b864?w=1200&q=80&auto=format&fit=crop",
    alt: "A clinician holding a tablet while talking with someone in a medical setting.",
    unsplashId: "NSBxHRFCvzc",
    unsplashPage: "https://unsplash.com/photos/man-in-white-dress-shirt-holding-black-tablet-computer-NSBxHRFCvzc",
    credit: {
      name: "National Cancer Institute",
      url: "https://unsplash.com/@nci",
    },
  },
  scenePharmacy: {
    url: "https://images.unsplash.com/photo-1698365140635-42894e5e63b4?w=1200&q=80&auto=format&fit=crop",
    alt: "Shelves lined with many glass and plastic bottles in a historic pharmacy.",
    unsplashId: "JDAR_lH5dPU",
    unsplashPage: "https://unsplash.com/photos/a-shelf-filled-with-lots-of-different-types-of-bottles-JDAR_lH5dPU",
    credit: {
      name: "Martina Jorden",
      url: "https://unsplash.com/@martinaj",
    },
  },
  sceneDischargePapers: {
    url: "https://images.unsplash.com/photo-1631217873436-b0fa88e71f0a?w=1200&q=80&auto=format&fit=crop",
    alt: "A clinician holding a tablet during a consultation with a patient.",
    unsplashId: "J_993suZjc0",
    unsplashPage: "https://unsplash.com/photos/man-in-white-button-up-shirt-holding-white-tablet-computer-J_993suZjc0",
    credit: {
      name: "National Cancer Institute",
      url: "https://unsplash.com/@nci",
    },
  },
  sceneFamilyPhone: {
    url: "https://images.unsplash.com/photo-1758273706126-6dd87b8f0f68?w=1200&q=80&auto=format&fit=crop",
    alt: "An adult on a video call on a smartphone while relaxing on a couch at home.",
    unsplashId: "Lts61JcSD9Q",
    unsplashPage: "https://unsplash.com/photos/woman-watching-video-call-on-smartphone-while-relaxing-on-couch-Lts61JcSD9Q",
    credit: {
      name: "Vitaly Gariev",
      url: "https://unsplash.com/@silverkblack",
    },
  },
} as const;
